plonky2/Cargo.toml
plonky2/benches/hashing.rs
plonky2/benches/merkle.rs
plonky2/src/hash/hash_types.rs

And one for a single Keccak hash

Add Merkle tree benchmark

---

plonky2/src/fri/prover.rs
plonky2/src/hash/gmimc.rs
plonky2/src/hash/hashing.rs
plonky2/src/hash/keccak.rs
plonky2/src/hash/merkle_proofs.rs
plonky2/src/hash/merkle_tree.rs
plonky2/src/hash/path_compression.rs
plonky2/src/hash/poseidon.rs
plonky2/src/plonk/circuit_builder.rs
plonky2/src/plonk/config.rs
plonky2/src/plonk/get_challenges.rs
plonky2/src/plonk/proof.rs
plonky2/src/plonk/prover.rs

And other tweaks to `MerkleTree::new`

Have hash functions take references to avoid cloning

---

field/src/polynomial/division.rs
plonky2/src/fri/oracle.rs

Remove `PolynomialBatch::compute_quotient()` and replace it with simple calls to `PolynomialCoeffs::divide_by_linear()` since we don't divide by higher degree polynomials anymore.
Also update the division tests to reflect that.

Remove `compute_quotient` and update division tests

---

plonky2/src/util/mod.rs
util/src/lib.rs
util/src/transpose_util.rs

Implements a cache-friendly bit-order reversal algorithm. (description of said algorithm to go here…)
Benchmark changes (arrays of `u64`s):
| length   | change |
| -------- | ------ |
|      256 |   -19% |
|    65536 |   -56% |
| 16777216 |   -75% |

Jakub does in 200 lines what can be done in 5 (bit-order reversal optimizations)

---

field/src/field_types.rs
field/src/polynomial/mod.rs
plonky2/src/fri/proof.rs
plonky2/src/fri/verifier.rs
plonky2/src/hash/merkle_proofs.rs
plonky2/src/iop/challenger.rs
plonky2/src/plonk/get_challenges.rs
plonky2/src/plonk/mod.rs
plonky2/src/plonk/plonk_common.rs
plonky2/src/plonk/proof.rs
plonky2/src/plonk/verifier.rs
starky/src/constraint_consumer.rs
starky/src/fibonacci_stark.rs
starky/src/get_challenges.rs
starky/src/lib.rs
starky/src/proof.rs
starky/src/prover.rs
starky/src/stark.rs
starky/src/verifier.rs
system_zero/src/core_registers.rs
system_zero/src/permutation_unit.rs
system_zero/src/system_zero.rs

Start of the STARK verifier. Also adds a `FriChallenges` struct used in `ProofChallenges` and `StarkProofChallenges`, and a distinction between wrapping and non-wrapping constraints.

Start of the STARK verifier

---

plonky2/src/fri/recursive_verifier.rs
plonky2/src/iop/challenger.rs
plonky2/src/plonk/get_challenges.rs
plonky2/src/plonk/prover.rs
starky/src/get_challenges.rs
starky/src/proof.rs
starky/src/prover.rs

Makes the challenger code more generic and simplifies the STARK code.

Replace `observe_opening_set` by `observe_openings` taking a `FriOpenings`

---

plonky2/src/util/reducing.rs

Tests in `plonky2/src/util/reducing.rs` relied on constants to populate the witness, which led to some operations being optimized away. This fixes the issue by using the `PartialWitness` instead.

Fix reducing tests

---

field/src/polynomial/mod.rs
starky/src/prover.rs
starky/src/stark_testing.rs
starky/src/verifier.rs

Also adds a test for `eval_l_1_and_l_last`.

Add a `PolynomialValues::selector` method for convenience

---

plonky2/src/fri/challenges.rs
plonky2/src/fri/mod.rs
plonky2/src/fri/witness_util.rs
plonky2/src/iop/challenger.rs
plonky2/src/iop/witness.rs

I think it would be nice to eventually have separate crates for IOP, FRI, PLONK, etc. This is one step toward that. No functional changes.

Move some FRI stuff into the FRI module

---

field/src/extension_field/quadratic.rs
field/src/extension_field/quartic.rs
field/src/field_types.rs
field/src/goldilocks_field.rs
field/src/inversion.rs
field/src/prime_field_testing.rs
field/src/secp256k1_base.rs
field/src/secp256k1_scalar.rs
plonky2/src/curve/curve_msm.rs
plonky2/src/curve/curve_multiplication.rs
plonky2/src/curve/curve_types.rs
plonky2/src/curve/secp256k1.rs
plonky2/src/gadgets/nonnative.rs
plonky2/src/gates/assert_le.rs
plonky2/src/gates/comparison.rs
plonky2/src/gates/subtraction_u32.rs
plonky2/src/hash/hash_types.rs
plonky2/src/hash/poseidon.rs
plonky2/src/hash/poseidon_goldilocks.rs
plonky2/src/iop/generator.rs
plonky2/src/iop/witness.rs
plonky2/src/util/serialization.rs
waksman/src/sorting.rs

And move some methods to them, as per the TODOs added in #454. No functional changes.

Add `PrimeField`, `PrimeField64` traits

---

system_zero/src/alu/subtraction.rs
system_zero/src/registers/alu.rs

Implementation of subtraction for the System Zero VM.

System Zero subtraction operation

---

plonky2/src/plonk/recursive_verifier.rs
plonky2/src/util/serialization.rs

The `add_virtual_proof` and `write_fri_initial_proof` functions do not take salting into account, which leads to bugs when using ZK.
Thanks to @Shalevos for catching this! Fixes #514.

Fix salt issues

---

field/src/zero_poly_coset.rs
plonky2/src/fri/oracle.rs
plonky2/src/plonk/prover.rs
plonky2/src/util/reducing.rs
starky/src/permutation.rs
starky/src/prover.rs
starky/src/vanishing_poly.rs

Vectorize constraint evaluation in Starky

---

field/src/polynomial/division.rs
field/src/polynomial/mod.rs

Fix `inv_mod_xn` so that it works on constant polynomials.
Fixes #519.

Fix inv mod xn

---

field/src/prime_field_testing.rs
plonky2/benches/ffts.rs
plonky2/examples/bench_recursion.rs

Fix new clippy lints

---

system_zero/src/alu/bitops.rs
system_zero/src/alu/mod.rs
system_zero/src/alu/rotate_shift.rs
system_zero/src/registers/alu.rs

This PR adds support for the ROTATE_LEFT, ROTATE_RIGHT, SHIFT_LEFT and SHIFT_RIGHT instructions to the System Zero VM.

System Zero bit rotate and shift operations

---

README.md

The paper was moved in https://github.com/mir-protocol/plonky2/commit/52faa0ceb7f52551f6c5f6e4f9c776234a35a2d0.

README.md: Update plonky2 paper link

---

evm/src/all_stark.rs
evm/src/cross_table_lookup.rs
evm/src/get_challenges.rs
evm/src/permutation.rs
evm/src/proof.rs
evm/src/recursive_verifier.rs
evm/src/stark.rs
evm/src/vanishing_poly.rs
evm/src/verifier.rs
plonky2/src/fri/witness_util.rs
plonky2/src/iop/ext_target.rs
plonky2/src/iop/target.rs
plonky2/src/plonk/plonk_common.rs

Implement circuit for the `evm` verifier.

`evm` recursive verifier

---

evm/src/all_stark.rs
evm/src/keccak/keccak_stark.rs
evm/src/keccak/registers.rs
evm/src/prover.rs

Add input registers to Keccak for wiring with Cpu table.

Keccak input registers

---

evm/src/all_stark.rs
evm/src/cross_table_lookup.rs
evm/src/keccak/keccak_stark.rs
evm/src/keccak/registers.rs
evm/src/prover.rs
evm/src/recursive_verifier.rs
evm/src/vanishing_poly.rs
plonky2/src/gadgets/split_base.rs
starky/src/prover.rs

h/t @nbgl for the idea.
Modify the CTL argument to allow lookups of linear combinations of columns.

Linear combinations as columns in CTL 

---

evm/src/cpu/decode.rs

These constraints are not required for soundness. Thx @dlubarov for pointing this out!

Remove redundant constraints

---

evm/src/cross_table_lookup.rs

Need to check for every challenge.

Fix CTL verification

---

evm/src/all_stark.rs
evm/src/cpu/cpu_stark.rs
evm/src/keccak/keccak_stark.rs
evm/src/logic.rs

Just cleaning up the code structure, as @wborgeaud suggested in a recent PR comment

Define columns for CTL closer to the constraints

---

evm/src/cpu/kernel/aggregator.rs
evm/src/cpu/kernel/asm/exp.asm

This doesn’t have a unit test, but I have tested it in an EVM simulator and it works

Exponentiation kernel function

---

evm/src/cpu/kernel/aggregator.rs
evm/src/cpu/kernel/asm/basic_macros.asm
evm/src/cpu/kernel/asm/exp.asm
evm/src/cpu/kernel/assembler.rs
evm/src/cpu/kernel/ast.rs
evm/src/cpu/kernel/evm_asm.pest
evm/src/cpu/kernel/parser.rs

See `basic_macros.rs` for an example. Will also let us write macros like `%mul_by(2)` which I think will be handy.
cc @nbgl

Macros with arguments

---

evm/src/all_stark.rs
evm/src/cross_table_lookup.rs

Provide better errors when the CTL check fails by manually performing the multiset check.

Better CTL errors

---

evm/src/prover.rs

Instead of quadratic evaluation. Should speed up `test_all_stark`.

Use FFTs to get subgroup evaluations in `check_constraints`

---

evm/src/memory/memory_stark.rs

This should improve cache locality - since we generally access several values at a time in a given row, we want them to be close together in memory. Also avoids the extra transposes we were doing previously.
There are a few steps that make more sense column-wise, though, such as generating the `COUNTER` column. I put those after the transpose.

Generate most of the memory table while it's in row-wise form

---

evm/src/cpu/kernel/interpreter.rs

Check that JUMPDEST is not in push data and implement STOP opcode.

Fix interpreter JUMPDEST check + change stopping behavior

---

evm/src/cpu/kernel/asm/basic_macros.asm
evm/src/cpu/kernel/assembler.rs
evm/src/cpu/kernel/ast.rs
evm/src/cpu/kernel/evm_asm.pest
evm/src/cpu/kernel/parser.rs

Add `%rep` syntax for repeating a block

---

ecdsa/src/gadgets/curve_fixed_base.rs

Could also be fixed by adding a `constant_affine_point_unchecked` function, but I think it's good practice to check for zero input.

Fix bug where `constant_affine_point` is called on zero

---

plonky2/src/iop/challenger.rs

Alternate implementation of #633, using `SPONGE_RATE` as the buffer size.

Use a fixed input buffer size in `Challenger`.

---

Cargo.toml
evm/Cargo.toml
evm/src/memory/memory_stark.rs
evm/src/permutation.rs
evm/src/proof.rs
evm/src/prover.rs
maybe_rayon/Cargo.toml
maybe_rayon/src/lib.rs
plonky2/Cargo.toml
plonky2/examples/bench_recursion.rs
plonky2/src/fri/oracle.rs
plonky2/src/fri/prover.rs
plonky2/src/hash/merkle_tree.rs
plonky2/src/plonk/permutation_argument.rs
plonky2/src/plonk/proof.rs
plonky2/src/plonk/prover.rs
starky/Cargo.toml
starky/src/permutation.rs
starky/src/proof.rs
starky/src/prover.rs

Part of https://github.com/mir-protocol/plonky2/issues/615

add rayon shim

---

evm/src/cpu/kernel/asm/util/basic_macros.asm

Will be used later for things like updating `MemorySize`.

min, max macros

---

field/Cargo.toml
field/src/extension/quadratic.rs
field/src/extension/quartic.rs
field/src/extension/quintic.rs
field/src/goldilocks_field.rs
field/src/secp256k1_base.rs
field/src/secp256k1_scalar.rs
field/src/types.rs
plonky2/Cargo.toml
plonky2/src/gates/mod.rs
plonky2/src/hash/hash_types.rs

feature-gate rand

---

evm/Cargo.toml
evm/benches/stack_manipulation.rs
evm/src/cpu/kernel/assembler.rs
evm/src/cpu/kernel/mod.rs
evm/src/cpu/kernel/stack/mod.rs
evm/src/cpu/kernel/stack/permutations.rs
evm/src/cpu/kernel/stack/stack_manipulation.rs

Using a method @SyxtonPrime described. This is mainly his idea and code, I just ported it to Rust.

For permutations, find the optimal sequence of swaps

---

evm/src/cpu/columns/mod.rs
evm/src/cpu/kernel/aggregator.rs
evm/src/cpu/kernel/asm/core/bootloader.asm
evm/src/cpu/kernel/asm/core/call.asm
evm/src/cpu/kernel/asm/core/create.asm
evm/src/cpu/kernel/asm/core/create_addresses.asm
evm/src/cpu/kernel/asm/core/intrinsic_gas.asm
evm/src/cpu/kernel/asm/core/nonce.asm
evm/src/cpu/kernel/asm/core/process_txn.asm
evm/src/cpu/kernel/asm/core/terminate.asm
evm/src/cpu/kernel/asm/core/transfer.asm
evm/src/cpu/kernel/asm/core/util.asm
evm/src/cpu/kernel/asm/keccak.asm
evm/src/cpu/kernel/asm/memory/metadata.asm
evm/src/cpu/kernel/asm/transactions/process_normalized.asm
evm/src/cpu/kernel/interpreter.rs
evm/src/cpu/kernel/tests/core/create_addresses.rs
evm/src/cpu/kernel/tests/core/intrinsic_gas.rs
evm/src/cpu/kernel/tests/core/mod.rs
evm/src/cpu/kernel/tests/mod.rs
evm/src/memory/segments.rs

With lots of TODOs to fill in afterward; this is just a start.
Depends on #651.

Core transaction processing logic

---

field/src/goldilocks_extensions.rs

Minor issue noticed by our auditors.

Tweak comments

---

evm/src/constraint_consumer.rs
evm/src/prover.rs
starky/src/constraint_consumer.rs
starky/src/prover.rs

Fix starky avx

---

field/src/fft.rs
field/src/interpolation.rs
field/src/polynomial/mod.rs

I.e. that it is the length of some power-of-two subgroup.

Check each `PolynomialValues` len

---

evm/src/all_stark.rs
evm/src/cpu/cpu_stark.rs
evm/src/cross_table_lookup.rs

In hindsight we may not need this feature.

Revert "Support accessing local row in CTLs"

---

plonky2/src/plonk/circuit_builder.rs

As per suggestion from our auditors.

Include degree in circuit digest

---

evm/src/arithmetic/add.rs
evm/src/arithmetic/arithmetic_stark.rs
evm/src/arithmetic/columns.rs
evm/src/arithmetic/compare.rs
evm/src/arithmetic/mod.rs
evm/src/arithmetic/sub.rs
evm/src/arithmetic/utils.rs

Use the subtraction operation to implement unsigned less than and greater than operations. A small amount of refactoring was involved.

EVM arithmetic unit: unsigned comparisons

---

evm/src/all_stark.rs
evm/src/cross_table_lookup.rs
evm/src/generation/mod.rs
evm/src/get_challenges.rs
evm/src/proof.rs
evm/src/prover.rs
evm/src/recursive_verifier.rs

Add a `NUM_TABLES` constant (replacing the current `Table::num_tables()`) and replace all `Vec<T>` indexed by tables with `[T; NUM_TABLES]`.

`NUM_TABLES` constant

---

evm/src/all_stark.rs
evm/src/cpu/columns/general.rs
evm/src/cpu/columns/mod.rs
evm/src/cpu/cpu_stark.rs
evm/src/cpu/jumps.rs
evm/src/cpu/simple_logic/eq_iszero.rs
evm/src/cpu/simple_logic/not.rs
evm/src/cpu/syscalls.rs
evm/src/generation/state.rs

Transpose memory columns (make it an array of channel structs)

---

evm/src/cpu/columns/mod.rs
evm/src/cross_table_lookup.rs
evm/src/keccak_sponge/columns.rs
evm/src/keccak_sponge/keccak_sponge_stark.rs
evm/src/keccak_sponge/mod.rs
evm/src/lib.rs
evm/src/stark_testing.rs
evm/src/util.rs
field/src/polynomial/mod.rs

It contains a row for each absorb step of the sponge.
I had some mostly-finished assembly for this, but this should be much more efficient.

Keccak sponge STARK

---

plonky2/src/fri/prover.rs

The speedup was well under a millisecond, so it's rather negligible, but I think the code is a little nicer this way also.

Compute answers to FRI queries in parallel

---

evm/src/cpu/kernel/asm/curve/bn254/curve_add.asm
evm/src/cpu/kernel/asm/curve/bn254/curve_mul.asm
evm/src/cpu/kernel/asm/curve/common.asm
evm/src/cpu/kernel/asm/curve/secp256k1/curve_add.asm
evm/src/cpu/kernel/asm/curve/secp256k1/curve_mul.asm
evm/src/cpu/kernel/asm/curve/secp256k1/ecrecover.asm
evm/src/cpu/kernel/asm/exp.asm
evm/src/cpu/kernel/asm/memory/memcpy.asm
evm/src/cpu/kernel/asm/rlp/decode.asm
evm/src/cpu/kernel/asm/rlp/read_to_memory.asm
evm/src/cpu/kernel/asm/transactions/router.asm
evm/src/cpu/kernel/asm/transactions/type_0.asm
evm/src/cpu/kernel/asm/transactions/type_1.asm
evm/src/cpu/kernel/asm/transactions/type_2.asm
evm/src/cpu/kernel/asm/util/assertions.asm
evm/src/cpu/kernel/interpreter.rs

We decided not to enforce it in kernel code.

Remove `JUMPDEST`s

---

evm/Cargo.toml
starky/Cargo.toml

Tweak features

---

plonky2/src/fri/oracle.rs
plonky2/src/fri/structure.rs

Give better documentation for the `PolynomialBatch::prove_openings` function as per auditor comments.

Document batch opening function

---

projects/cache-friendly-fft/__init__.py
projects/cache-friendly-fft/transpose.py
projects/cache-friendly-fft/util.py

Python implementation of the cache-oblivious FFT algorithm. Can be ported to Rust by whoever needs a project.

Python prototype of cache-oblivious FFT

---

evm/src/arithmetic/compare.rs

Gets rid of a few "not implemented" warnings

Verify that comparison output is zero or one

---

evm/src/all_stark.rs
evm/src/cpu/columns/mod.rs
evm/src/cpu/cpu_stark.rs
evm/src/cpu/membus.rs
evm/src/cpu/mod.rs
evm/src/memory/mod.rs

Add `context` column and connect the decoder to memory

Memory channel for decode

---

evm/src/cpu/kernel/asm/memory/packing.asm
evm/src/cpu/kernel/asm/rlp/encode.asm
evm/src/cpu/kernel/tests/packing.rs

I.e. have `mstore_unpacking` return the updated position.

Minor refactor of RLP code

---

evm/src/cpu/kernel/aggregator.rs
evm/src/cpu/kernel/asm/rlp/encode.asm
evm/src/cpu/kernel/asm/rlp/num_bytes.asm
evm/src/cpu/kernel/tests/rlp/mod.rs
evm/src/cpu/kernel/tests/rlp/num_bytes.rs

Since it's in some code paths where speed is critical.

Unroll num_bytes

---

evm/src/arithmetic/modular.rs
evm/src/arithmetic/mul.rs
evm/src/arithmetic/utils.rs
evm/src/lib.rs

This PR refactors `mul.rs` (and some of its touch points) in terms of the functions created for modular operations in #755.

Refactor and tidy up `mul.rs`

---

evm/Cargo.toml
evm/src/cpu/kernel/tests/mpt/hash.rs
evm/src/cpu/kernel/tests/mpt/insert.rs
evm/src/cpu/kernel/tests/mpt/load.rs
evm/src/cpu/kernel/tests/mpt/mod.rs

Bumped `eth_trie_utils` to `0.2.0`. There were a few public API changes, so I ended up updating the callsites in the tests so that it compiles. I also did a bit of refactoring to reduce code duplication in the tests, so let me know what you think about these changes.

Updated `eth_trie_utils` to `0.2.1`

---

evm/Cargo.toml
evm/src/cpu/kernel/aggregator.rs
evm/src/cpu/kernel/asm/mpt/hash.asm
evm/src/cpu/kernel/asm/mpt/hash_trie_specific.asm
evm/src/cpu/kernel/asm/mpt/load.asm
evm/src/cpu/kernel/asm/mpt/load_trie_specific.asm
evm/src/cpu/kernel/constants/context_metadata.rs
evm/src/cpu/kernel/constants/global_metadata.rs
evm/src/cpu/kernel/tests/mpt/hash.rs
evm/src/cpu/kernel/tests/mpt/insert.rs
evm/src/cpu/kernel/tests/mpt/load.rs
evm/src/cpu/kernel/tests/mpt/read.rs
evm/src/generation/mpt.rs
evm/src/memory/segments.rs

I.e. have leaves in the state trie point to the root of a storage trie

Treat storage tries as sub-tries of the state trie

---

evm/src/cpu/membus.rs

This was missing but is required for correctness (it is used as a filter in a CTL).

Constrain `mem_channel.used` flag to be binary

---

util/Cargo.toml
util/src/lib.rs

Thanks to Least Authority for this

Test reverse_index_bits

---

plonky2/src/plonk/circuit_builder.rs

As William suggested; resolves #456.

Randomize unused wires of PublicInputGate

---

plonky2/src/plonk/circuit_builder.rs

Domain separator option

---

plonky2/src/recursion/cyclic_recursion.rs

Inverting `base_case` so that the API becomes very similar to `conditionally_verify_proof_or_dummy`, and expanding docs a bit.

Cyclic recursion tweaks

---

README.md
evm/Cargo.toml
evm/src/lib.rs
plonky2/Cargo.toml
system_zero/Cargo.toml

Also update the version used elsewhere.

Jemalloc for EVM

---

evm/src/cpu/cpu_stark.rs
evm/src/cpu/memio.rs
evm/src/cpu/mod.rs
evm/src/cpu/stack.rs
evm/src/generation/mod.rs
evm/src/witness/operation.rs

Constraints for `mload_general` and `mstore_general`, as well as corresponding witness generation.

Memory load/store constraints

---

evm/Cargo.toml
system_zero/Cargo.toml
util/Cargo.toml

Some deps were moved to `[dev-dependencies]`. Very small amount, and I deliberated a bit if it was even worth a PR.

Moved some deps to `[dev-dependencies]`

---

evm/src/all_stark.rs
evm/src/cross_table_lookup.rs
evm/src/recursive_verifier.rs
evm/src/verifier.rs

We ended up not needing the feature.

Remove CTL defaults

---

evm/src/generation/prover_input.rs

h/t @npwardberkeley for pointing this out.

Use error instead of panicking in `FromStr`

---

evm/src/fixed_recursive_verifier.rs
plonky2/src/gates/selectors.rs
plonky2/src/plonk/circuit_data.rs

I had to make some things public in order to use struct-update syntax for the anticipated `CommonCircuitData`.
cc @BGluth FYI

Block circuit

---

.github/workflows/continuous-integration-workflow.yml
evm/src/cross_table_lookup.rs
evm/src/fixed_recursive_verifier.rs
evm/src/permutation.rs
evm/src/prover.rs
evm/src/recursive_verifier.rs
evm/src/vanishing_poly.rs
evm/src/verifier.rs
plonky2/benches/field_arithmetic.rs
plonky2/examples/bench_recursion.rs
plonky2/src/fri/challenges.rs
plonky2/src/fri/proof.rs
plonky2/src/fri/recursive_verifier.rs
plonky2/src/hash/merkle_tree.rs
plonky2/src/iop/ext_target.rs
plonky2/src/plonk/get_challenges.rs
plonky2/src/plonk/proof.rs
plonky2/src/plonk/prover.rs
plonky2/src/plonk/vanishing_poly.rs
plonky2/src/plonk/verifier.rs
plonky2/src/recursion/conditional_recursive_verifier.rs
plonky2/src/recursion/cyclic_recursion.rs
plonky2/src/recursion/dummy_circuit.rs
plonky2/src/recursion/recursive_verifier.rs
starky/src/permutation.rs
starky/src/prover.rs
starky/src/recursive_verifier.rs
starky/src/vanishing_poly.rs
starky/src/verifier.rs

This reverts commit da23fb116b934925f8a5cf37c2f1f092452fdc4d.

Revert "Set CI to use an older version of nightly"

---

evm/src/cpu/kernel/asm/hash/blake2b/addresses.asm
evm/src/cpu/kernel/asm/hash/blake2b/compression.asm
evm/src/cpu/kernel/asm/hash/blake2b/g_functions.asm
evm/src/cpu/kernel/asm/hash/blake2b/hash.asm
evm/src/cpu/kernel/asm/hash/blake2b/iv.asm
evm/src/cpu/kernel/asm/hash/blake2b/permutations.asm
evm/src/cpu/kernel/tests/hash.rs

Replacing macros with function calls
Reduces kernel size by 50% 🤯

Optimize blake2b

---

evm/src/cpu/kernel/asm/core/create_addresses.asm
evm/src/generation/mod.rs
evm/src/generation/outputs.rs
evm/src/generation/state.rs
evm/src/generation/trie_extractor.rs
evm/src/prover.rs
evm/src/witness/memory.rs
evm/src/witness/operation.rs
evm/tests/basic_smart_contract.rs
evm/tests/empty_txn_list.rs
evm/tests/simple_transfer.rs

Which returns information about the post-state after execution. This is useful for debugging purposes.
cc @cpubot

Add a `prove_with_outputs` method

---

evm/src/cpu/kernel/asm/balance.asm
evm/src/cpu/kernel/asm/core/syscall_stubs.asm

Test `GeneralStateTests/stSelfBalance/selfBalance.json` gives the correct state (but incorrect state trie root for now)

Implement syscalls for BALANCE and SELFBALANCE

---

evm/src/cpu/kernel/asm/account_code.asm
evm/src/cpu/kernel/asm/core/syscall_stubs.asm
evm/src/cpu/kernel/asm/memory/metadata.asm
evm/src/cpu/kernel/asm/memory/syscalls.asm
evm/src/cpu/kernel/asm/memory/txn_fields.asm

Implement sys_origin, sys_calldatasize, sys_calldatacopy, sys_codecopy, sys_returndatasize, sys_returndatacopy, sys_coinbase, sys_timestamp, sys_number, sys_gaslimit, sys_basefee.

Implement various syscalls

---

evm/src/witness/operation.rs

By returning a MemoryError instead.

Avoid panicking in mstore

---

evm/Cargo.toml
evm/src/cpu/kernel/constants/trie_type.rs
evm/src/cpu/kernel/tests/account_code.rs
evm/src/cpu/kernel/tests/balance.rs
evm/src/cpu/kernel/tests/mpt/hash.rs
evm/src/cpu/kernel/tests/mpt/insert.rs
evm/src/cpu/kernel/tests/mpt/load.rs
evm/src/cpu/kernel/tests/mpt/mod.rs
evm/src/generation/mod.rs
evm/src/generation/mpt.rs
evm/src/generation/trie_extractor.rs
evm/src/lib.rs
evm/tests/add11_yml.rs
evm/tests/basic_smart_contract.rs
evm/tests/empty_txn_list.rs
evm/tests/simple_transfer.rs

Updated the library to use the new version of `eth_trie_utils`.

Bumped `eth_trie_utils` to `0.5.0`

---

plonky2/src/iop/challenger.rs

Since the structs themselves have `[(); HC::WIDTH]:`.

Remove extra conditions

---

evm/src/cpu/kernel/asm/memory/syscalls.asm

MSTORE8 only stores the least significant byte.

Fix MSTORE8

---

evm/src/cpu/kernel/asm/core/terminate.asm
evm/src/cpu/kernel/asm/memory/metadata.asm

Also set returndata size to 0 in sys_stop and sys_selfdestruct.

Implement sys_return and sys_revert

---

evm/src/cpu/cpu_stark.rs
evm/src/cpu/decode.rs

Fixes the constraints in `decode.rs`.

Fix decode constraint

---

evm/src/cpu/kernel/interpreter.rs

This PR implements some block related operations in the interpreter

Block interpreter

---

evm/src/cpu/kernel/interpreter.rs

This PR implements the remaining (signed) arithmetic operations on the interpreter's side.

Implement arithmetic opcodes on the interpreter side

---

evm/src/keccak_sponge/columns.rs
evm/src/keccak_sponge/keccak_sponge_stark.rs

Following Daniel's suggestion in #950.

Remove is_final_block column in KeccakSpongeStark

---

evm/src/cpu/kernel/interpreter.rs

This PR implements some environment instructions on the interpreter side.

Env instructions in interpreter

---

evm/tests/basic_smart_contract.rs
evm/tests/self_balance_gas_cost.rs

They're slow on CI, and `add11_yml` seems like a better integration test.

Disable a couple tests

---

evm/src/cpu/kernel/asm/core/precompiles/bn_add.asm
evm/src/cpu/kernel/asm/core/precompiles/bn_mul.asm
evm/src/cpu/kernel/asm/core/precompiles/ecrec.asm
evm/src/cpu/kernel/asm/core/precompiles/id.asm
evm/src/cpu/kernel/asm/core/precompiles/main.asm
evm/src/cpu/kernel/asm/core/precompiles/rip160.asm
evm/src/cpu/kernel/asm/core/precompiles/sha256.asm
evm/src/cpu/kernel/asm/core/process_txn.asm

Add logic to handle calls from an EOA to a precompile.

EOA to precompiles logic

---

evm/src/cpu/kernel/asm/core/create.asm
evm/src/cpu/kernel/asm/core/process_txn.asm
evm/src/cpu/kernel/constants/mod.rs

Also added cost of deploying code in `process_contract_creation_txn_after_constructor`.

EIP-170: Contract code size limit 

---

evm/src/cpu/kernel/asm/core/precompiles/main.asm
evm/src/cpu/kernel/asm/core/util.asm

Precompiles exist

---

evm/src/cpu/kernel/asm/account_code.asm
evm/src/cpu/kernel/asm/core/call.asm
evm/src/cpu/kernel/asm/core/terminate.asm
evm/src/cpu/kernel/asm/memory/metadata.asm
evm/src/cpu/kernel/asm/memory/syscalls.asm
evm/src/cpu/kernel/asm/util/keccak.asm

This PR addresses the overflow risks mentioned in the discussion [here](https://github.com/mir-protocol/plonky2/pull/930/files/a4ea0965d79561c345e2f77836c07949c7e0bc69#r1143630253).

Address overflow-related TODOs in ASM code.

---

plonky2/examples/bench_recursion.rs

It seems latest nightly is triggering a new error with clippy.

Fix clippy

---

evm/src/cpu/kernel/asm/core/create.asm
evm/src/cpu/kernel/asm/core/create_contract_account.asm
evm/src/cpu/kernel/asm/core/transfer.asm

All `stCreate2/create2collision*` tests now pass.

Fix issues related to CREATE2 collisions

---

evm/src/cpu/kernel/aggregator.rs
evm/src/cpu/kernel/asm/core/log.asm
evm/src/cpu/kernel/asm/core/syscall_stubs.asm

Added a TODO to actually implement the receipts logic

Implement LOG* gas and remove panic

---

evm/src/cpu/kernel/asm/core/syscall_stubs.asm

Fill `BLOCKHASH` and `PREVRANDAO` syscalls with dummy code

---

evm/src/cpu/kernel/asm/core/syscall_stubs.asm

Useful to make some tests pass

Implement PREVRANDAO as if it was DIFFICULTY

---

evm/src/cpu/kernel/asm/core/create.asm

See `stCreate2/Create2OnDepth1024` for a relevant test.

Check call depth in CREATE

---

evm/src/cpu/kernel/asm/core/precompiles/snarkv.asm
evm/src/cpu/kernel/asm/curve/bn254/curve_arithmetic/final_exponent.asm
evm/src/cpu/kernel/asm/curve/bn254/curve_arithmetic/miller_loop.asm
evm/src/cpu/kernel/asm/curve/bn254/curve_arithmetic/pairing.asm
evm/src/cpu/kernel/asm/curve/bn254/field_arithmetic/degree_12_mul.asm
evm/src/cpu/kernel/asm/curve/bn254/field_arithmetic/inverse.asm
evm/src/cpu/kernel/asm/curve/bn254/field_arithmetic/util.asm
evm/src/generation/prover_input.rs
evm/src/witness/util.rs

Use current context for pairing memory

---

evm/src/witness/operation.rs

This is just #1115 (thanks @hratoanina) but removes an unnecessary case

Fix `generate_exception` (#1115 replacement)

---

field/src/extension/quadratic.rs
field/src/extension/quartic.rs
field/src/extension/quintic.rs
field/src/goldilocks_field.rs
field/src/secp256k1_base.rs
field/src/secp256k1_scalar.rs
field/src/types.rs

Implement the TODOs and move `from_noncanonical_u64` and `from_noncanonical_i64` from `Field64` to `Field`.

Move operations to Field

---

plonky2/src/util/mod.rs

I did some tests and found that this version of transpose is more efficient, significantly reducing the time to run prove().
For example, I have a recursive circuit with 1024x sha256 calls that takes ~110s to prove. With this patch it goes down to 93s!

Optimize transpose

---

evm/src/witness/operation.rs

We noticed that modfp254.rs constraints, as well as CTL checks were failing in the test (from evm-tests) `create2callPrecompiles_5`. This was due to the fact that in `generate_binary_arithmetic_op`, the modulus limbs were not stored in the `row`. 
On the `ArithmeticStark` side, the `fp254` operations are considered as ternary operations, and therefore the CTL checks include `input0`, `input1` as well as the modulus (= `BN_BASE` in the fp254 case). Moreover, modfp254.rs introduces constraints on the modulus in `CpuStark`. For those two reasons, in this PR, we write `BN_BASE` limbs in the cpu row, in `generate_binary_arithmetic_op` when necessary.

Fill modulus limbs in cpu row for Fp254 operations.

---

evm/src/arithmetic/addcy.rs

The function to which the addcy code delegates does not check that `given_cy` is in fact 0 or 1, and this check was overlooked in the calling code.

Better document constraints on addcy carries

---

evm/src/cpu/stack.rs

Constrain keccak general

---

evm/src/fixed_recursive_verifier.rs
evm/src/get_challenges.rs
evm/src/prover.rs
evm/src/recursive_verifier.rs
evm/tests/add11_yml.rs
evm/tests/simple_transfer.rs
plonky2/src/iop/challenger.rs

Deals with the TODO on observing public values when generating challenges.
Note that I had to update some tests as we'd have a cast overflow otherwise.

Observe PublicValues

---

evm/src/keccak/keccak_stark.rs

Adds a missing constraint that ensures the upper limb of the preimage is same across rows
Related to https://github.com/mir-protocol/plonky2/issues/1133#issuecomment-1690366448

fix: constrain higher bits of reg_preimage

---

evm/tests/log_opcode.rs

Just cleans up a bit the `test_log_with_aggreg` from the previous PR.

Remove duplicate code

---

evm/src/keccak/keccak_stark.rs

Keccak STARK: constrain preimage to equal A on first round

---

evm/src/cpu/cpu_stark.rs
evm/src/cpu/jumps.rs
evm/src/cpu/simple_logic/eq_iszero.rs
evm/src/cpu/simple_logic/mod.rs
evm/src/cpu/stack.rs

Constrain `nv.stack_len` in `cpu/stack.rs`.

Constrain next row's stack length

---

evm/src/cpu/cpu_stark.rs
evm/src/keccak_sponge/keccak_sponge_stark.rs

Missing cleanup from #1246's review.

Follow-up cleanup from #1246

---

evm/src/arithmetic/columns.rs
evm/src/byte_packing/columns.rs
evm/src/memory/columns.rs

Those haven't been updated post `logUp` upgrade.

minor: Fix description of RC related columns in STARK modules

---

evm/src/cpu/kernel/optimizer.rs
evm/src/cpu/kernel/stack/stack_manipulation.rs

Latest nightly updated formatting rules, causing CI on `main` to fail.

Apply rustfmt with latest nightly

---

evm/src/cpu/kernel/asm/core/exception.asm
evm/src/cpu/kernel/asm/core/syscall.asm
evm/src/cpu/kernel/asm/memory/syscalls.asm
evm/src/cpu/kernel/interpreter.rs
evm/src/witness/transition.rs

Relies on a similar logic than the `wcopy`-related syscalls (and hence may benefit partly from their incoming refactoring).
@wborgeaud apologies for the harassment the past few days 🙏🏼 This isn't targeting main, so no need to deal with it urgently!
closes #1267

Implement EIP-5656 (MCOPY)

---

evm/tests/selfdestruct.rs

Mainly to have a test that performs an account deletion.

Add test for selfdestruct

---

evm/src/memory/memory_stark.rs

Missing constraints in the Memory Stark.
We do not check that memory is initialized at 0, that is to say that a read at a new address without a prior write must have a value of 0.
An immediate exploit is to bypass JUMPDEST analysis in case of a jump outside of the contract code, and subsequently arbitrary code execution in the uninitialized memory. In https://github.com/topos-protocol/plonky2/tree/code_injection, the code of the contract is a jump to address 0x80 which should raise an invalid jump exception, but the transaction is accepted and the proof is valid.

Constrain uninitialized memory to 0

---

evm/src/cpu/kernel/aggregator.rs
evm/src/cpu/kernel/asm/core/withdrawals.asm
evm/src/cpu/kernel/asm/main.asm
evm/src/generation/mod.rs
evm/src/generation/prover_input.rs
evm/src/generation/state.rs
evm/src/witness/errors.rs
evm/tests/add11_yml.rs
evm/tests/basic_smart_contract.rs
evm/tests/erc20.rs
evm/tests/log_opcode.rs
evm/tests/many_transactions.rs
evm/tests/self_balance_gas_cost.rs
evm/tests/selfdestruct.rs
evm/tests/simple_transfer.rs
evm/tests/withdrawals.rs

Add withdrawals as a public input array of `address, amount`. See EIP-4895.

Add withdrawals

---

evm/src/cpu/kernel/interpreter.rs
evm/src/witness/mod.rs
evm/src/witness/transition.rs

Remove duplicate code from #1348.

Remove unnecessary code duplication

---

evm/src/cpu/kernel/interpreter.rs
evm/src/generation/mpt.rs

Light code reading resulted in some lightweight fixes.

Root out some unwraps

---

field/src/arch/x86_64/avx2_goldilocks_field.rs

Nightly has added more clippy rules.

Make clippy happy

---

evm/src/cpu/columns/mod.rs
evm/src/cpu/gas.rs
evm/src/cpu/jumps.rs
evm/src/cpu/syscalls_exceptions.rs
evm/src/fixed_recursive_verifier.rs
evm/src/generation/mod.rs
evm/src/get_challenges.rs
evm/src/proof.rs
evm/src/recursive_verifier.rs
evm/src/witness/operation.rs
evm/src/witness/transition.rs

This reverts commit 0f19cd0dbc25f9f1aa8fc325ae4dd1b95ca933b3.
This change was added for testing purposes only, but isn't intended to be kept in the long term. Now that all RC1 items are merged, this can be reverted.

Revert "Make gas fit in 2 limbs (#1261)"

---

evm/src/fixed_recursive_verifier.rs
evm/src/proof.rs
evm/tests/empty_txn_list.rs

@BGluth This PR initializes the block hashes of the genesis block.

Initialize blockhashes

---

evm/src/cpu/halt.rs

Extra check to prevent malicious halting while executing user code.

Check is_kernel_mode when halting

---

evm/src/fixed_recursive_verifier.rs
evm/tests/empty_txn_list.rs
evm/tests/log_opcode.rs

Fix genesis block number on the `prove_block` side + add sanity check.

Fix genesis block number in `prove_block`

---

README.md

Added a Discord badge to the `README.md` that people can use to join the Polygon Zero Discord server.
Thanks to [ppoliani](https://github.com/ppoliani) for suggesting in #1431!

Added a Discord badge to `README.md`

---

evm/src/cpu/kernel/interpreter.rs

Minor cleanup from #1393.
@LindaGuiga would you mind reviewing?

Minor cleanup

---

evm/Cargo.toml

Bumped `eth_trie_utils`

---

starky/src/prover.rs

Latest clippy complaining for no reason

Pacify clippy

---

evm/src/generation/mod.rs

Fix an error in the user's code simulation used by jumpdest analysis.

Fix simulation for jumpdest analysis

---

evm/src/cpu/kernel/asm/core/touched_addresses.asm

Addresses an oversight from previous changes.

Fix `touched_addresses` removal

---

evm/src/cpu/kernel/interpreter.rs

In the interpreter, `run_jump` and `run_jumpi` were not throwing the correct exceptions. This PR changes the two functions so that they correspond to the logic in `operation.rs`. 
Note that this also removes an unnecessary `assert_ne!` which suggests to calm `KECCAK256` if the segment is `MainMemory` in `KECCAK_GENERAL`; since the `sys_keccak256` calls `KECCAK_GENERAL` and the interpreter now relies directly on the kernel syscalls, the assert is no longer useful (and causes unnecessary failures).

Fix interpreter jumps

---

evm/src/cpu/kernel/asm/bignum/add.asm
evm/src/cpu/kernel/asm/bignum/addmul.asm
evm/src/cpu/kernel/asm/bignum/cmp.asm
evm/src/cpu/kernel/asm/bignum/modmul.asm
evm/src/cpu/kernel/asm/bignum/mul.asm
evm/src/cpu/kernel/asm/bignum/shr.asm
evm/src/cpu/kernel/asm/bignum/util.asm
evm/src/cpu/kernel/asm/hash/blake2/addresses.asm
evm/src/cpu/kernel/asm/hash/sha2/compression.asm
evm/src/cpu/kernel/asm/hash/sha2/main.asm
evm/src/cpu/kernel/asm/hash/sha2/message_schedule.asm
evm/src/cpu/kernel/asm/hash/sha2/write_length.asm
evm/src/cpu/kernel/asm/memory/core.asm
evm/src/cpu/kernel/asm/util/basic_macros.asm
evm/src/generation/prover_input.rs

Amortize calls to `modexp` precompile by ~5%.

Improve `BIGNUM` operations

---

util/src/lib.rs

This get triggered when running plonky2 in wasm32-wasi target.

Use wrapping_shr in reverse_index_bits_in_place_small

---

plonky2/src/hash/poseidon.rs

For use in the `type-2` branch, though I figured it may be coming in handy for external users as well to have this available.

Add additional methods for Poseidon with PackedField

---

plonky2/src/plonk/circuit_builder.rs

Methods needed for continuation.

Add hash public input methods

---

starky/src/cross_table_lookup.rs

only found one, the repo is typo free now, congrats

chore: typo fix

---

util/Cargo.toml

Missed bumping this crate in the previous PR for new version release.

Bump plonky2-util version

---

maybe_rayon/src/lib.rs
plonky2/src/fri/oracle.rs
plonky2/src/util/reducing.rs

Reverts 0xPolygonZero/plonky2#1571

Revert "Optimize reduce_polys_base "

---

.github/pr_checking.yml

cf internal discussion
cc @Freyskeyd, thank you for the template!

ci: add PR check job

---

plonky2/src/plonk/circuit_builder.rs

fix: changed conditioning for timing functionality in circuit_builder

---

plonky2/src/util/serialization/gate_serialization.rs

fix: correct visibility in gate_serialization macros

---

plonky2/src/gates/lookup.rs
plonky2/src/gates/lookup_table.rs
plonky2/src/plonk/vanishing_poly.rs

Fix for issue 0xPolygonZero/security#2

Fix padding in LookupTableGate
