0xPolygonZero/plonky2

plonky2/src/hash/hash_types.rs

`CircuitBuilder`'s hashing gadgets currently take a `Vec<Target>` and return a `HashOutTarget` but there's no way to turn the `HashOutTarget` back into a `Vec<Target>`.
I made `elements` public so the user can do `hash_out.elements.to_vec()`. I also made `from_vec` and `from_partial` public for the same reason.

make `HashOutTarget`'s `elements` public

---

plonky2/src/util/mod.rs
util/src/lib.rs

These changes halve the ASM size for `log2_strict` and `log2_ceil`. I also added some tests.

Optimize + test log2 functions

---

Cargo.toml
plonky2/Cargo.toml

This fixes a warning about the profiles in the [`plonky2/Cargo.toml`](https://github.com/mir-protocol/plonky2/blob/main/plonky2/Cargo.toml) file by moving them to the to the top level workspace toml file (this issue probably arose in the recent crate refactor). The profiles themselves just set optimisation levels to the defaults, and so the fact that they were ignored didn't cause any issues.
The only concern might be publishing "subcrates", which might not inherit the profile correctly, as described in
https://github.com/rust-lang/cargo/issues/8264.

Move profile definitions to root workspace toml.

---

plonky2/src/fri/oracle.rs
plonky2/src/fri/recursive_verifier.rs
plonky2/src/fri/verifier.rs
plonky2/src/plonk/circuit_builder.rs

In our FRI-based polynomial commitment, we commit to polynomials of degree `< n` and use a low-degree test to check that `(f - f(z)) / (X - z)` has degree `< n` (where `f` is a linear combination of the original polynomials). 
However, this quotient polynomial has degree `deg(f)-1`. So by starting with polynomials of degree `n`, the LDT would pass. This could potentially be exploited.
This PR fixes this by multiplying the quotient by `X`, so that the LDT actually checks that the quotient has degree `< n-1`.

Fix degree of polynomial used in LDT

---

field/src/fft.rs
field/src/interpolation.rs
field/src/polynomial/mod.rs
plonky2/benches/ffts.rs
plonky2/src/fri/oracle.rs
util/src/lib.rs

Perform FFTs without cloning vectors.
While it is ready for review, this PR should not be merged yet. It turns out that `reverse_index_bits_in_place` is significantly slower than its out-of-place counterpart. This disparity can and should be fixed, but until that happens, merging this PR would actually make proofs slower.

Make all FFTs in-place

---

plonky2/src/plonk/prover.rs

This change appears to improve the loops' cache/paging characteristics. It doesn't matter for reasonable problem sizes, but the current ordering causes a large slowdown for problems that don't fit in memory.
Fixes #443.

Swap loops in `compute_quotient_polys`

---

plonky2/src/fri/proof.rs
plonky2/src/fri/prover.rs
plonky2/src/fri/recursive_verifier.rs
plonky2/src/gadgets/polynomial.rs
plonky2/src/hash/merkle_proofs.rs
plonky2/src/plonk/circuit_builder.rs
plonky2/src/plonk/circuit_data.rs
plonky2/src/plonk/proof.rs
plonky2/src/plonk/recursive_verifier.rs
plonky2/src/plonk/verifier.rs

With a `add_virtual_proof_with_pis` method that uses the inner circuit data, but does not require constructing a proof.
Note that this doesn't support IVC type patterns (where a single circuit can be used for any proof in a PCD graph) yet. For that, I think we can add a variant of `add_virtual_proof_with_pis` that takes several parameters like FRI arities, but does not involve `CommonCircuitData` (since no circuit has been build yet). It might also be best to avoid large objects like `FriParams`, and pass just the data we need.
Then there will be some nontrivial work to do recursion with "estimated" parameters (degree, arities, etc), check if the estimates were correct, and try again if not.

Replace `proof_to_proof_target`

---

plonky2/src/iop/witness.rs
plonky2/src/plonk/recursive_verifier.rs

Same code as before, except I broke it into a few functions and renamed a couple things.
Resolves #431.

Make `set_proof_target` publicly accessible

---

plonky2/src/hash/hashing.rs
plonky2/src/hash/merkle_tree.rs

Getting around the overhead of Rayon's parallel iterators when building Merkle Trees. These changes speed up Merkle Tree benchmarks by 5% for width 2 ** 15 and 8% for width 2 ** 13 (both on Poseidon) on my machine. Speeds up proofs by 2%. (In general, there's more benefit for smaller trees and for machines with more cores.)

Merkle tree optimizations

---

field/src/arch/x86_64/avx2_goldilocks_field.rs
field/src/arch/x86_64/avx512_goldilocks_field.rs
field/src/field_types.rs
field/src/goldilocks_field.rs
field/src/inversion.rs
field/src/prime_field_testing.rs
plonky2/src/bin/generate_constants.rs
plonky2/src/gadgets/arithmetic.rs
plonky2/src/gadgets/arithmetic_extension.rs
plonky2/src/gates/assert_le.rs
plonky2/src/gates/base_sum.rs
plonky2/src/gates/comparison.rs
plonky2/src/gates/subtraction_u32.rs
plonky2/src/hash/arch/aarch64/poseidon_goldilocks_neon.rs
plonky2/src/hash/hash_types.rs
plonky2/src/hash/poseidon.rs
plonky2/src/hash/poseidon_goldilocks.rs
plonky2/src/util/serialization.rs
waksman/src/sorting.rs

And add TODOs for moving around various methods which aren't well-defined in their current traits, or would be well-defined in a supertrait.

Rename `PrimeField` -> `Field64`

---

plonky2/src/gadgets/curve.rs
plonky2/src/plonk/recursive_verifier.rs

`test_curve_mul` takes quite some time in the CI. Recursive tests should be pretty fast now that we run the tests with `opt-level=3`.

Ignore `test_curve_mul` and unignore recursive tests

---

plonky2/src/plonk/circuit_builder.rs

Circuits using a small number of low-degree gates can have `max_filtered_constraint_degree = 2`, in which case the current code panics when searching for the best value of `quotient_degree_factor` (since `num_partial_products` isn't defined when the max degree is 1). 
This is fixed by starting the search for `quotient_degree_factor` at 2 in such cases.

Disallow `quotient_degree_factor = 1`

---

plonky2/src/hash/merkle_tree.rs

Addresses part of #463. Prints a better message when panicking because the cap height is too large. Fixes the panic that would occur when `cap_height == log2(leaves.len())`.

Merkle tree bugfixes + tests

---

plonky2/src/plonk/prover.rs
starky/src/fibonacci_stark.rs
starky/src/lib.rs
starky/src/prover.rs
starky/src/stark.rs
starky/src/stark_testing.rs
starky/src/verifier.rs
system_zero/src/system_zero.rs

Adds a `fn degree(&self) -> usize` method to the `Stark` trait and use it to get the minimal number of quotient polynomial chunks.
Also adds a test `test_stark_low_degree` to check the degree of the STARK constraints, analogous to `test_low_degree` for gates.

Stark constraint degree

---

plonky2/src/plonk/prover.rs

Note that this still does not permit batch sizes that are not a multiple of the packing length used for the field. This will require separate changes to `gates:packed_util::PackedEvaluableBase`.

Permit small circuits in `compute_quotient_polys`

---

plonky2/src/fri/prover.rs
plonky2/src/fri/recursive_verifier.rs
plonky2/src/hash/hashing.rs
plonky2/src/hash/keccak.rs
plonky2/src/hash/merkle_proofs.rs
plonky2/src/hash/merkle_tree.rs
plonky2/src/hash/path_compression.rs
plonky2/src/hash/poseidon.rs
plonky2/src/iop/challenger.rs
plonky2/src/plonk/circuit_builder.rs
plonky2/src/plonk/config.rs
plonky2/src/plonk/proof.rs
plonky2/src/plonk/prover.rs
plonky2/src/plonk/recursive_verifier.rs

This should be a tad better for for performance, and lets us do padding in a generic way, rather than each hash reimplementing it.
This also disables padding for public inputs. It seems unnecessary since the number of public inputs is fixed for any given instance.

Separate methods for hashing with or without padding

---

field/src/polynomial/mod.rs
plonky2/src/plonk/prover.rs
starky/src/prover.rs

Seems a little nicer IMO to only remove a certain number of zeros, vs removing all trailing zeros then re-adding some.

`trim_to_len` helper function

---

plonky2/src/fri/witness_util.rs
plonky2/src/iop/witness.rs
plonky2/src/plonk/recursive_verifier.rs

Most functions used to fill the witness are of the form `set_X_target(xt: XTarget, x: X)`.
`set_proof_target`, `set_proof_with_pis_target`, and `set_fri_proof_target` currently use the opposite parameter order.
This PR fixes that.

Standardize `set_*` method parameter order

---

plonky2/src/fri/challenges.rs
plonky2/src/fri/proof.rs
plonky2/src/fri/recursive_verifier.rs
plonky2/src/plonk/get_challenges.rs
plonky2/src/plonk/proof.rs
plonky2/src/plonk/recursive_verifier.rs
plonky2/src/plonk/verifier.rs

The native and recursive verifiers currently do not have the same structure. For example, the native verifier first computes all challenges, while the recursive verifier computes these challenges in the middle of other verification steps.
This PR unifies the code of the native and recursive verifier, making it easier to audit and providing a common structure also for the STARK (recursive) verifier.

Match native and recursive verifier structures

---

plonky2/src/curve/ecdsa.rs
plonky2/src/gadgets/ecdsa.rs

Derives a few traits for the ecdsa types. `Debug` was the one that was causing a few problems in the client, but I thought we might as well also derive the traits that are derived on the underlying types.

Added `Debug`, `Clone`, and `Copy` to ecdsa types

---

plonky2/src/hash/hash_types.rs
plonky2/src/hash/hashing.rs

This was causing a few calls in the client to allocate a `Vec` when we didn't need to.

`from_partial` now takes in a slice

---

plonky2/src/curve/curve_types.rs
plonky2/src/curve/ecdsa.rs
plonky2/src/curve/secp256k1.rs

The client needed a few more derives on the ecdsa types. `Serialize` & `Deserialze` were the critical ones, but I also thought it was a good idea to also derive `PartialEq`, `Eq`, and `Hash` where I could.
Few notes:
- I didn't add any of the derives on the circuit versions since it was going to require adding a lot more derives on types that I wasn't sure should be implementing the traits.
- Not sure if it makes sense to derive `PartialEq` & `Eq` on `Secp256K1`, a unit struct. It seems wrong to declare that you can compare two unit structs against each other, but this seems to be required if we want to construct `ECDSASecretKey<Secp256K1>`.
- Right now since we're deriving these traits directly on the ecdsa types, we're enforcing that any curves used also implement these traits. If we …

Derived more traits for ecdsa types

---

plonky2/src/curve/curve_types.rs
plonky2/src/curve/ecdsa.rs

Oversight on my part. The client ended up needed `Hash` on `AffinePoint` since public keys are hashed in numerous places.

Impled `Hash` for `AffinePoint`

---

system_zero/src/arithmetic/addition.rs
system_zero/src/arithmetic/division.rs
system_zero/src/arithmetic/mod.rs
system_zero/src/arithmetic/multiplication.rs
system_zero/src/arithmetic/subtraction.rs
system_zero/src/core_registers.rs
system_zero/src/permutation_unit.rs
system_zero/src/system_zero.rs

I didn't really have a good reason for putting there; seems more idiomatic to make them global since they don't need `self`/`Self`.
Also tweak some generic bounds that seemed more restrictive than necessary.
No functional changes.

Move some methods outside `impl System`

---

plonky2/benches/merkle.rs
plonky2/src/fri/oracle.rs
plonky2/src/fri/proof.rs
plonky2/src/fri/prover.rs
plonky2/src/fri/verifier.rs
plonky2/src/gates/gate_testing.rs
plonky2/src/hash/hashing.rs
plonky2/src/hash/merkle_proofs.rs
plonky2/src/hash/merkle_tree.rs
plonky2/src/hash/path_compression.rs
plonky2/src/plonk/circuit_builder.rs
plonky2/src/plonk/circuit_data.rs
plonky2/src/plonk/config.rs
plonky2/src/plonk/proof.rs
plonky2/src/plonk/prover.rs
plonky2/src/plonk/recursive_verifier.rs
plonky2/src/plonk/verifier.rs
starky/src/prover.rs
starky/src/verifier.rs

Fix bugs (introduced in #341) where a `hash_no_pad` is used instead of a `hash_or_noop` for Merkle tree leaves.

Use `hash_or_noop` for Merkle tree leaves

---

field/src/polynomial/mod.rs
starky/src/get_challenges.rs
starky/src/lib.rs
starky/src/permutation.rs
starky/src/proof.rs
starky/src/prover.rs
starky/src/recursive_verifier.rs
starky/src/stark.rs
starky/src/verifier.rs
system_zero/src/system_zero.rs

It's slightly complex because we batch `constraint_degree - 1` permutation arguments into a single `Z` polynomial. This is a slight generalization of the [technique](https://zcash.github.io/halo2/design/proving-system/lookup.html) described in the Halo2 book.
Without this batching, we would simply have `num_challenges` random challenges (betas and gammas). With this batching, however, we need to use different randomness for each permutation argument within the same batch. Hence we end up generating `batch_size * num_challenges` challenges for all permutation arguments.

Prover code for permutation argument

---

starky/src/constraint_consumer.rs
starky/src/fibonacci_stark.rs
system_zero/src/alu/addition.rs
system_zero/src/alu/mod.rs
system_zero/src/core_registers.rs
system_zero/src/permutation_unit.rs

Most of our constraints apply to all rows, and it seems safest to make that the "default".
cc @nbgl fyi

Rename constraint methods

---

system_zero/Cargo.toml
system_zero/src/alu/addition.rs
system_zero/src/alu/canonical.rs
system_zero/src/alu/mod.rs
system_zero/src/alu/mul_add.rs
system_zero/src/alu/multiplication.rs
system_zero/src/registers/alu.rs

The inputs are assumed to be `u32`s, while the output is encoded as four `u16` limbs. Each output limb is range-checked.
So, our basic mul-add constraint looks like
out_0 + 2^16 out_1 + 2^32 out_2 + 2^48 out_3 = in_1 * in_2 + in_3
The right hand side will never overflow, since `u32::MAX * u32::MAX + u32::MAX < |F|`. However, the left hand side could overflow, since it can be any 64-bit value.
For example, an operation like `0 * 0 + 0` could have two possible outputs, 0 and `|F|`, both of which would satisfy the constraint above. To prevent these non-canonical outputs, we need a comparison to enforce that `out < |F|`.
Thankfully, `F::MAX` has all zeros in its low 32 bits, so `x <= F::MAX` is equivalent to `x_lo == 0 || x_hi != u32::MAX`. `x_hi != u32::MAX` can be checked by showing that …

Implement a mul-add circuit in the ALU

---

plonky2/src/hash/arch/aarch64/mod.rs
plonky2/src/hash/arch/aarch64/poseidon_goldilocks_neon.rs
plonky2/src/hash/poseidon_goldilocks.rs

Vectorized full round MDS for the new matrix. Minor changes to full S-boxes.

Restore vectorization to full Poseidon rounds on Aarch64

---

system_zero/src/alu/mul_add.rs

@nbgl noticed it's missing. Filtering the check-canonical constraint will be non-trivial, so just adding a TODO for now.

Filter mul-add constraints

---

starky/src/get_challenges.rs
starky/src/lib.rs
starky/src/prover.rs
starky/src/recursive_verifier.rs
starky/src/verifier.rs
system_zero/src/alu/division.rs
system_zero/src/alu/mul_add.rs
system_zero/src/alu/subtraction.rs
system_zero/src/lib.rs
system_zero/src/permutation_unit.rs
system_zero/src/system_zero.rs

Most of them were trivial to address; for the remaining warnings I suppressed just the relevant line and added TODOs.

Stop suppressing unused/dead warnings globally

---

starky/src/proof.rs
starky/src/stark.rs

`degree_bits` is needed by `add_virtual_stark_proof_with_pis` when building a plonky2 SNARK that verifies a starky STARK proof. Therefore the user needs `recover_degree_bits` to be public.
I also added a doc comment to `eval_ext_recursively` to clear up #538.

Make `recover_degree_bits` public

---

evm/src/all_stark.rs
evm/src/cross_table_lookup.rs
evm/src/get_challenges.rs
evm/src/proof.rs
evm/src/prover.rs
evm/src/verifier.rs

Make some `evm` structs more generic to reduce friction when adding new tables.

Make some `evm` structs more generic

---

evm/src/all_stark.rs
evm/src/keccak/keccak_stark.rs

Fix a bug in Keccak STARK where the input copy constraints shouldn't be applied on the last permutation round.

Fix constraint in Keccak STARK

---

evm/src/prover.rs

`get_lde_values_packed` was loading points from the Merkle tree, which contains evaluations on a coset, rather than the subgroup.

Fix `check_constraints` to only look at subgroup points

---

evm/Cargo.toml

Upgrades the `itertools` dependency to version `0.10.3`. That’s the first release that includes `multiunzip`. The build fails with older versions.

Fix EVM dependency list

---

evm/src/all_stark.rs
evm/src/logic.rs
evm/src/util.rs

Uses the linear combination `Column` API to do CTL directly between limbs in the CPU table and bits in the logic table. Removes 32 columns from the logic table.

CTL: limbs (CPU) <-> bits (logic)

---

evm/src/cpu/kernel/aggregator.rs
evm/src/cpu/kernel/asm/basic_macros.asm
evm/src/cpu/kernel/asm/exp.asm
evm/src/cpu/kernel/assembler.rs
evm/src/cpu/kernel/ast.rs
evm/src/cpu/kernel/evm_asm.pest
evm/src/cpu/kernel/parser.rs

Also recognize global labels as a `PUSH` target; previously it only considered local labels.

ASM macro support

---

evm/src/all_stark.rs
evm/src/cpu/columns.rs
evm/src/cpu/cpu_stark.rs
evm/src/memory/memory_stark.rs
evm/src/memory/mod.rs
evm/src/memory/registers.rs

- Define the channel count and value limbs in a single place, so they're easy to adjust.
- Standardize on "channels" which I think is more explicit, since e.g. `num_mem_ops` used to mean either the channel count or total operation count in a trace.

Memory naming tweaks

---

evm/Cargo.toml
evm/src/bin/assemble.rs
evm/src/cpu/kernel/assembler.rs
evm/src/cpu/kernel/mod.rs

This is just for debugging the kernel. It's fully disposable.

Util for assembling EVM code to hex

---

plonky2/src/fri/recursive_verifier.rs
plonky2/src/fri/verifier.rs
plonky2/src/gadgets/split_join.rs
plonky2/src/hash/merkle_proofs.rs
plonky2/src/hash/merkle_tree.rs

- Add `_to_cap` to existing methods for clarity
- Add variants which deal with Merkle roots instead of caps
- Simplify `verify_merkle_proof_to_cap` - it can call `verify_merkle_proof_to_cap_with_cap_index`
- Make them all public except `verify_merkle_proof_to_cap_with_cap_index`, which is pretty niche
Resolves #582.

Tweak Merkle proof API and make it public

---

evm/src/cpu/kernel/assembler.rs

Current implementation builds the global labels map incrementally, making it impossible to call a global label defined in a subsequent file.
Fixes this by building the labels map before calling the `assemble_file` function.

Find global labels before assembly

---

evm/src/cpu/kernel/aggregator.rs
evm/src/cpu/kernel/assembler.rs
evm/src/cpu/kernel/ast.rs
evm/src/cpu/kernel/evm_asm.pest
evm/src/cpu/kernel/mod.rs
evm/src/cpu/kernel/parser.rs

Roughly like environment variables. So we don't have to declare things like segment IDs twice.

Allow constants to be passed from Rust into our assembly

---

u32/src/gates/arithmetic_u32.rs

Closes #526. This PR introduces a canonicity check for the `U32ArithmeticGate` output, along with a test using a non-canonical output. (Best reviewed commit-by-commit.)

`U32ArithmeticGate`: constrain canonicity of output.

---

evm/src/memory/columns.rs
evm/src/memory/memory_stark.rs

By no longer storing unsorted operations; they are effectively stored in the CPU table already.
I ran into some issues with sorting, since the existing sort method didn't include `is_channel` columns. Rather than update the existing method, I removed it and added a sort on the `MemoryOp`s, which I think seems cleaner.

Simplify memory table

---

evm/src/generation/state.rs
evm/src/memory/columns.rs
evm/src/memory/memory_stark.rs

This adds padding rows which satisfy the ordering checks. To ensure that they also satisfy the value consistency checks, I just copied the address and value from the last operation.
I think this method of padding feels more natural, though it is a big more code since we need to calculate the max range check in a different way. But on the plus side, the constraints are a bit smaller and simpler.
Also added a few constraints that I think we need for soundness:
- Each `is_channel` flag is bool.
- Sum of `is_channel` flags is bool.
- Dummy operations must be reads (otherwise the prover could put writes in the memory table which aren't in the CPU table).

More realistic padding rows in memory table

---

evm/src/cpu/kernel/aggregator.rs
evm/src/cpu/kernel/assembler.rs

For now it doesn't log filenames, but we can compare against the list of filenames in `combined_kernel`.
Current output:
```
[DEBUG plonky2_evm::cpu::kernel::assembler] Assembled file size: 0 bytes
[DEBUG plonky2_evm::cpu::kernel::assembler] Assembled file size: 49 bytes
[DEBUG plonky2_evm::cpu::kernel::assembler] Assembled file size: 387 bytes
[DEBUG plonky2_evm::cpu::kernel::assembler] Assembled file size: 27365 bytes
[DEBUG plonky2_evm::cpu::kernel::assembler] Assembled file size: 0 bytes
[DEBUG plonky2_evm::cpu::kernel::assembler] Assembled file size: 11 bytes
[DEBUG plonky2_evm::cpu::kernel::assembler] Assembled file size: 7 bytes
[DEBUG plonky2_evm::cpu::kernel::aggregator::tests] Total kernel size: 27819 bytes
```
This shows that most of our kernel code is from `curve_add.asm`, …

Have `make_kernel` log the size of each (assembled) file

---

evm/Cargo.toml
evm/src/cpu/bootstrap_kernel.rs
evm/src/cpu/columns.rs
evm/src/cpu/kernel/aggregator.rs
evm/src/cpu/kernel/assembler.rs
evm/src/cpu/kernel/keccak_util.rs
evm/src/cpu/kernel/mod.rs
evm/src/generation/mod.rs
evm/src/generation/state.rs

The kernel is hashed using a Keccak based sponge for now. We could switch to Poseidon later if our kernel grows too large.
Note that we use simple zero-padding (pad0*) instead of the standard pad10* rule. It's simpler, and we don't care that the prover can add extra 0s at the end of the code. The program counter can never reach those bytes, and even if it could, they'd be 0 anyway given the EVM's zero-initialization rule.
In one CPU row, we can do a whole Keccak hash (via the CTL), absorbing 136 bytes. But we can't actually bootstrap that many bytes of kernel code in one row, because we're also limited by memory bandwidth. Currently we can write 4 bytes of the kernel to memory in one row.
So we treat the `keccak_input_limbs` columns as a buffer. We gradually fill up this buffer, 4 bytes …

Continue work on bootstrapping

---

evm/src/all_stark.rs
evm/src/cpu/bootstrap_kernel.rs
evm/src/cpu/kernel/aggregator.rs
evm/src/generation/memory.rs
evm/src/generation/state.rs
evm/src/memory/memory_stark.rs
evm/src/memory/segments.rs

It's a bit more type-safe (can't mix up segment with context or virtual addr), and this way uniqueness of ordinals is enforced, partially addressing a concern raised in #591.
To avoid making `Segment` public (which I don't think would be appropriate), I had to make some other visibility changes, and had to move `generate_random_memory_ops` into the test module.

Organize segments in an enum

---

evm/src/cpu/bootstrap_kernel.rs
evm/src/generation/memory.rs
evm/src/generation/state.rs
evm/src/memory/columns.rs
evm/src/memory/memory_stark.rs

Ultimately they're encoded as `[F; 8]`s in the table, but I don't anticipate that we'll have any use cases where we want to store more than 256 bits. Might as well store `U256` until we actually build the table since they're more compact.

Store memory values as `U256`s

---

evm/src/cpu/kernel/aggregator.rs
evm/src/cpu/kernel/asm/basic_macros.asm
evm/src/cpu/kernel/asm/memory.asm

This can be used, for example, to copy `CALL` data (which is a slice of the caller's main memory) to the callee's `CALLDATA` segment.
I'll add a test once we update the interpreter to handle other memory segments.

Implement memcpy

---

evm/src/cpu/kernel/asm/basic_macros.asm
evm/src/cpu/kernel/asm/memory.asm

Intended for loading constants in SHA2, and maybe RIPEMD (cc @typ3c4t).
Sample usage
```
// Loads the i'th K256 constant.
%macro k256
// stack: i
%mul_const(4)
// stack: 4*i
PUSH k256_data
// stack: k256_data, 4*i
ADD
// stack: k256_data + 4*i
%mload_kernel_code_u32
// stack: K256[4*i]
%endmacro
k256_data:
BYTES 0x42, 0x8a, 0x2f, 0x98
BYTES 0x71, 0x37, 0x44, 0x91
...
```
Untested for now since our interpreter doesn't have the needed memory support quite yet.

Add a `mload_kernel_code_u32` macro

---

evm/src/all_stark.rs
evm/src/cpu/columns.rs
evm/src/cpu/control_flow.rs
evm/src/cpu/cpu_stark.rs
evm/src/cpu/kernel/aggregator.rs
evm/src/cpu/kernel/asm/halt.asm
evm/src/cpu/mod.rs

Enforce correct control flow between rows. An execution trace is forced to occupy a contiguous range of rows. It begins at `program_counter = 0` and continues until the program halts (this is just a flag which we can set if the STOP instruction is executed or the program is killed). The `program_counter` of a row (unless it is the very first row of an execution trace) is set to `next_program_counter` from the previous row.

Inter-row program counter constraints

---

evm/src/all_stark.rs
evm/src/cpu/columns/mod.rs
evm/src/cpu/control_flow.rs

When we execute an instruction that takes up one row (is not microcoded), then we increment the program counter by 1.

Increment program counter on native instructions

---

evm/src/cpu/kernel/asm/transactions/type_0.asm

Always parse "to" as a scalar. No need for a branch; it's left over from when I was trying to enforce canonical RLP (in which case "to" must be 0 or 20 bytes).
The old code would be wrong if we had multiple txns per proof, as if to=0 we wouldn't write that field to memory, so it could have an old value from a previous txn.

Small fix for type 0 txns

---

evm/src/cpu/columns/mod.rs
evm/src/cpu/decode.rs

Make the proof unverifiable whenever the PANIC instruction is executed

Implement PANIC instruction

---

evm/src/cpu/kernel/assembler.rs
evm/src/cpu/kernel/ast.rs
evm/src/cpu/kernel/parser.rs
evm/src/cpu/kernel/stack_manipulation.rs

There's no syntax to distinguish named stack items from labels, so this simply searches the former first. I.e. labels can be shadowed by stack items.

Allow `%stack` to work with labels

---

evm/src/cpu/kernel/assembler.rs
evm/src/cpu/kernel/ast.rs
evm/src/cpu/kernel/mod.rs
evm/src/cpu/kernel/parser.rs
evm/src/cpu/kernel/stack_manipulation.rs
evm/src/cpu/kernel/utils.rs

Instead of the original strings. Will make optimizations simpler.
Depends on #646.

Store literals as `U256` (or `u8` for `BYTES`)

---

evm/src/cpu/kernel/interpreter.rs
evm/src/cpu/kernel/tests/mod.rs
evm/src/cpu/kernel/tests/rlp.rs
evm/src/cpu/kernel/tests/transaction_parsing/mod.rs
evm/src/cpu/kernel/tests/transaction_parsing/parse_type_0_txn.rs
evm/src/cpu/kernel/tests/type_0_txn.rs

The test didn't catch any bugs; it seems @wborgeaud already found them all for me :)
I made a couple related changes to `Interpreter`:
- Only enforce the `JUMPDEST` rule if we're in kernel mode.
- Flexibility to configure additional halt offsets, to help tests pieces of assembly which don't have the form of functions (i.e. they don't return to an address on the stack, so we can't pass `0xdeadbeef`).
- Convenience methods for dealing with the RLP and txn field segments of memory.

Test for parsing type 0 transactions

---

evm/src/cpu/kernel/aggregator.rs
evm/src/cpu/kernel/constants.rs
evm/src/cpu/kernel/context_metadata.rs
evm/src/cpu/kernel/global_metadata.rs
evm/src/cpu/kernel/interpreter.rs
evm/src/cpu/kernel/mod.rs
evm/src/cpu/kernel/tests/exp.rs
evm/src/cpu/kernel/tests/rlp.rs
evm/src/cpu/kernel/tests/transaction_parsing/parse_type_0_txn.rs
evm/src/memory/segments.rs

- `GlobalMetadata` - offsets for global kernel variables in memory
- `ContextMetadata` - offsets for context-specific kernel variables in memory
- `GAS_CONSTANTS`, based on the yellowpaper
Also move constants to a separate module since `aggregator` was getting long.
Depends on #650.

More constants for kernel ASM

---

plonky2/src/gates/exponentiation.rs
plonky2/src/gates/interpolation.rs
plonky2/src/gates/low_degree_interpolation.rs
plonky2/src/gates/mod.rs
plonky2/src/gates/random_access.rs
plonky2/src/gates/selectors.rs

Motivation: Since gates are in a `Vec` of trait objects and we want to allow people to implement their own gates outside the library, they need to be able to construct them in order to deserialize circuit data (see #590).

Make the rest of gates public

---

evm/src/cpu/kernel/aggregator.rs
evm/src/cpu/kernel/asm/memory/packing.asm
evm/src/cpu/kernel/interpreter.rs
evm/src/cpu/kernel/tests/mod.rs
evm/src/cpu/kernel/tests/packing.rs

Methods for encoding integers as bytes in memory, as well as the reverse, decoding bytes as integers. All big-endian.
Can be used for `MLOAD` later, but also for things like RLP, where integers get encoded as big-endian bytes.

Packing memory operations

---

evm/src/keccak/columns.rs
evm/src/keccak/keccak_stark.rs

Based on the approach @SyxtonPrime described.
In terms of columns, the changes are:
- Store inputs (`A`) as `u32` limbs, rather than individual bits.
- Remove `C_partial`. It was used to store an intermediate product in a 5-way xor, but we've since realized that we can do a 5-way xor directly.
- Add `C_prime`, an intermediate result used to help verify the relation between `A` and `A'`.

Improved Keccak implementation

---

evm/src/cpu/kernel/asm/transactions/type_0.asm

Some of the `%stack` operations are now trivial, but I kind of like keeping `%stack` since it serves as documentation as well, making comments about the stack unnecessary.

Make use of `mstore_txn_field` in type 0 parsing

---

evm/src/cpu/columns/general.rs
evm/src/cpu/columns/mod.rs
evm/src/cpu/simple_logic/eq_iszero.rs
evm/src/cpu/simple_logic/not.rs
evm/src/logic.rs

This was mostly trivial, except it required a rewrite of the `EQ` instruction (the previous method relied on the small limb size).

Change logic limb size to 32 bits

---

ecdsa/src/curve/curve_msm.rs
ecdsa/src/curve/curve_types.rs
ecdsa/src/curve/glv.rs
ecdsa/src/curve/secp256k1.rs
ecdsa/src/gadgets/curve_fixed_base.rs
ecdsa/src/gadgets/curve_msm.rs
ecdsa/src/gadgets/curve_windowed_mul.rs
ecdsa/src/gadgets/glv.rs
ecdsa/src/gadgets/nonnative.rs
field/src/extension/quadratic.rs
field/src/extension/quartic.rs
field/src/extension/quintic.rs
field/src/goldilocks_field.rs
field/src/secp256k1_base.rs
field/src/secp256k1_scalar.rs
field/src/types.rs

These appear to be unused for extension fields, so we're free to change the mapping without breaking anything.
As the TODO says, the mapping that's currently implemented doesn't seem natural or useful. It seems more natural to treat the `BigUint` as a base field element, potentially in a non-canonical form.
The new name `from_noncanonical_biguint` is meant to emphasize this behavior.

Change `from_biguint`'s behavior with extension fields

---

evm/src/cpu/kernel/context_metadata.rs
evm/src/cpu/kernel/global_metadata.rs
evm/src/memory/segments.rs

Summary of the design:
- Tries are stored as immutable, copy-on-write trees.
- All trie data is stored in the `TrieData` segment. Since it's immutable, data is never modified/deleted, new versions are just appended at the next unused offset.
- In order to support reverts, each context stores a pointer to the initial state trie version, plus pointers to the initial versions of each storage trie.
One variation which may be worth considering is storing the whole state trie as one big trie (with sub-tries for storage). Reverts would then be simpler - we'd replace a single pointer. I thought that approach might make hashing the trie a bit more complex, as the node associated with an account would be a special type of node, rather than just another leaf. Either approach seems reasonable though.

Trie related segments and metadata

---

ecdsa/src/gadgets/ecdsa.rs

`ECDSASecretKeyTarget` and `ECDSAPublicKeyTarget`'s fields are private, so you cannot initialize them outside this crate. `ECDSASecretKeyTarget` and `ECDSAPublicKeyTarget` are  parameters of `verify_message_circuit`, so they should be able to be initialized outside this crate.

Change visibility of `ECDSASecretKeyTarget` and `ECDSAPublicKeyTarget`'s fields

---

evm/src/all_stark.rs
evm/src/cpu/cpu_stark.rs
evm/src/cross_table_lookup.rs

Previously CTLs could only access the "next" row; this lets them access the "local" row as well.

Support accessing local row in CTLs

---

.github/workflows/continuous-integration-workflow.yml

Added caching to the CI workflows.
Under the hood, [rust-cache](https://github.com/Swatinem/rust-cache) calls GitHub's more generic [cache](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows) action with a configuration that makes sense for a Cargo project. The high level idea is this:
- Generate a cache key based on variables that would normally require a full/partial recompile (eg. compiler version, `Cargo.lock`, etc.).
- Check if there is a cache entry for this key.
- If the key is missing, then after the job completes, create a new cache entry for this key containing build artifacts (`~/.cargo` & `target/`).
- If the key exists, then copy the cached directories directly into the workflow container.
So for a cache hit, this should …

Added caching for GitHub Workflows

---

evm/src/cross_table_lookup.rs
evm/src/prover.rs

See this line -
```rust
challenges: ctl_data.challenges.challenges[i % config.num_challenges],
```
This doesn't work if we have multiple lookers from the same table; then `zs_columns` will contain multiple contiguous entries for the same challenge.
We could fix the index calculation, but it seems a bit error-prone. Seems easier to store the specific challenge as part of `zs_columns`.

Fix for CTL challenges

---

evm/src/all_stark.rs
evm/src/generation/state.rs
evm/src/memory/columns.rs
evm/src/memory/memory_stark.rs
evm/src/memory/mod.rs

Instead of having `NUM_CHANNELS` CTLs between the CPU and memory, we can have a single CTL with `NUM_CHANNELS` lookers, all from the CPU table.
This means the memory table no longer needs to know about channels, so we can simplify it a bit and combine its channel flags into a single flag (to distinguish "real" and "padding" rows).
Depends on #689.

Simpler CPU <-> memory CTL

---

evm/Cargo.toml
evm/src/keccak/columns.rs
evm/src/keccak/keccak_stark.rs

`keccak_rust` doesn't seem to have much usage, and it treats `x` as the major axis of its 5x5 input.  This is not exactly wrong, since Keccak itself doesn't have a notion of axis order. However, there is a convention for mapping bits of the cube to a flat list of bits, which is
> The mapping between the bits of `s` and those of `a` is `s[w(5y + x) + z] = a[x][y][z]`.
Obeying this convention would be awkward with `keccak_rust` - the words in memory would need to be transposed.

Remove keccak_rust in favor of tiny-keccak

---

evm/src/all_stark.rs
evm/src/cpu/columns/mod.rs
evm/src/cpu/decode.rs

The `opcode` column is just a linear combination of the `opcode_bits` columns, so we can delete it.

Delete opcode column

---

evm/src/proof.rs

Not needed since EVM proofs are wrapped in recursive proofs.

Remove compressed proofs in EVM crate

---

evm/Cargo.toml
evm/src/all_stark.rs
evm/src/cpu/columns/mod.rs
evm/src/cpu/cpu_stark.rs
evm/src/cross_table_lookup.rs
evm/src/generation/state.rs
evm/src/keccak_memory/columns.rs
evm/src/keccak_memory/keccak_memory_stark.rs
evm/src/keccak_memory/mod.rs
evm/src/lib.rs
evm/src/prover.rs
evm/src/recursive_verifier.rs
evm/src/verifier.rs

The Keccak permutation's inputs/outputs are larger than our CPU's memory bandwidth, so we can't do Keccak-f in a single cycle.
This introduces a Keccak memory table to sit between the CPU and Keccak tables. The CPU table can pass it just a start address, and this table will handle all the necessary memory lookups.

Keccak memory stark

---

evm/src/all_stark.rs
evm/src/cpu/columns/general.rs
evm/src/cpu/cpu_stark.rs
evm/src/cpu/jumps.rs
evm/src/cpu/simple_logic/eq_iszero.rs
evm/src/cpu/simple_logic/not.rs
evm/src/cpu/syscalls.rs
evm/src/logic.rs

Removes all the various `input`/`output` columns, and puts constraints directly on memory values

Make jumps, logic, and syscalls read from/write to memory columns

---

ecdsa/src/gadgets/biguint.rs
ecdsa/src/gadgets/curve_fixed_base.rs
ecdsa/src/gadgets/glv.rs
ecdsa/src/gadgets/nonnative.rs
u32/src/gadgets/arithmetic_u32.rs
u32/src/witness.rs

Having to import and directly call a `witness_set_u32_target` function is a bit clunky.
Instead, add the  functions to a `WitnessU32` subtrait of `Witness` and do a blanket `impl WitnessU32 for T where T: Witness` for it.
in other words, we go from this:
```rust
use plonky2_u32::witness_set_u32_target;
let mut pw = PartialWitness::new();
witness_set_u32_target(&mut pw, val);
```
to this:
```rust
use plonky2_32::WitnessU32;
let mut pw = PartialWitness::new();
pw.set_u32_target(val);
```
I Also did the same for `BigUint` in `ecdsa` and something similar for `GeneratedValues`.

cleaner interface for witness extension methods in `u32` and `ecdsa`

---

evm/src/generation/partial_trie.rs

A downstream project needed `Hash` on `Nibbles`, but I also thought it made sense to derive a few other core traits as well.

Added a few derives to `Trie` types

---

evm/Cargo.toml
maybe_rayon/src/lib.rs
plonky2/src/hash/hash_types.rs
starky/Cargo.toml

In #678 I used `rayon`'s `flat_map_iter` but I forgot to add it to `maybe_rayon`'s `ParallelIteratorMock` trait, which breaks `starky` and `evm` when the `parallel` feature is disabled. This PR fixes that.
This PR also fixes `starky` and `evm` not disabling default features for `plonky2`, which causes `rayon` to be enabled even if it's disabled by `starky` and `evm`, and it also fixes a feature gate for `BytesHash`.

Add `flat_map_iter` to `maybe_rayon`

---

evm/src/cpu/columns/mod.rs
evm/src/cpu/control_flow.rs
evm/src/cpu/cpu_stark.rs
evm/src/cpu/mod.rs
evm/src/cpu/stack_bounds.rs

Adds a stack pointer and constraints to show that the current instruction will not cause the stack to underflow or overflow.
Note that this does not actually add the kernel routines to handle underflow or overflow. Until this happens, any such error will cause the proof to be unverifiable.

Stack pointer + underflow/overflow checks

---

evm/src/recursive_verifier.rs
evm/src/verifier.rs
field/src/zero_poly_coset.rs
plonky2/src/plonk/plonk_common.rs
plonky2/src/plonk/vanishing_poly.rs
starky/src/recursive_verifier.rs
starky/src/verifier.rs

Change `L_1` to `L_0` everywhere to match the conventional notation `L_i(g^i) = 1`.

Change Lagrange polynomial notation 

---

plonky2/src/iop/generator.rs
plonky2/src/iop/witness.rs
plonky2/src/plonk/circuit_builder.rs
plonky2/src/plonk/circuit_data.rs

Virtual targets are only a prover specific thing and the prover already has access to this info via `ProverOnlyCircuitData::representative_map`.

Remove `num_virtual_targets` from `CommonCircuitData`

---

field/src/extension/mod.rs

As observed by an auditor, `DTH_ROOT=0` is not a  `D`th root of unity. Fixed by setting it to `1`.

Fix `DTH_ROOT` for degree 1 extension

---

evm/src/cpu/kernel/assembler.rs
evm/src/cpu/kernel/ast.rs
evm/src/cpu/kernel/stack/stack_manipulation.rs

They weren't being expanded, as @typ3c4t found.

Fix macro vars in `%stack` directives

---

evm/src/generation/mod.rs
evm/tests/transfer_to_new_addr.rs

Added a mapping between an account's `code_hash` field and the actual contract byte code in `GenerationInputs`.

Added a mapping between code hashes and contract byte code

---

plonky2/src/gates/base_sum.rs
util/src/lib.rs

As observed by auditors, the current way of computing the number of limbs in `BaseSumGate` allows for overflows.

Fix `num_limbs` in `BaseSumGate`

---

evm/Cargo.toml
evm/src/cpu/kernel/interpreter.rs
evm/src/generation/mod.rs
evm/src/generation/mpt.rs
evm/src/proof.rs
evm/src/recursive_verifier.rs
evm/src/util.rs

`H256` preserves any leading `0`s, which could be critical in some situations. Also just a slightly more appropriate type for hashes.

Trie roots now use `H256` instead of `U256`

---

evm/src/cpu/kernel/asm/sha2/compression.asm
evm/src/cpu/kernel/asm/sha2/constants.asm

I think `%mload_kernel_code_u32` is good when we need to do random access, but since the indices are constant here, let's just hardcode them like this.
This reduces the assembled size of `compression.asm` from 1827 to 1454 bytes. I think there's still a lot more we could do to shrink it, though it's not that important.

Inline some SHA2 constants

---

evm/src/cpu/kernel/asm/ripemd/main.asm
evm/src/cpu/kernel/tests/hash.rs

The problem was downstream of an error in my simplification of the original Python implementation. The original paldength definition was:
```python
x = 64 - length % 64
if x < 9:
x += 64
return x - 8
```
and in my Python code, I had made the error of computing it as
```py
x = 56 - length % 64
return x + (x < 9)*64
```
where I subtracted `64 - 8 = 56` but still checked `x < 9`, rather than what should have been `x < 1`
Note that, to avoid overflow, in the asm it's now
```py
t = length % 64
return 56 + 64*(t > 55) - t
```
where before the check was `t > 47`

Fix RipeMD padlength issue

---

evm/src/recursive_verifier.rs
plonky2/examples/bench_recursion.rs
plonky2/src/plonk/circuit_builder.rs
plonky2/src/plonk/circuit_data.rs
plonky2/src/plonk/get_challenges.rs
plonky2/src/plonk/prover.rs
plonky2/src/plonk/recursive_verifier.rs
plonky2/src/plonk/verifier.rs

`degree_bits` is a field of `FriParams` and `CommonCircuitData`, but `FriParams` is also a field of `CommonCircuitData`, so there's some (unchecked) redundancy.
Fixed that by removing `degree_bits` from `CommonCircuitData`.

Redundant `degree_bits`

---

evm/src/cpu/kernel/asm/curve/secp256k1/ecrecover.asm
evm/src/cpu/kernel/asm/rlp/decode.asm
evm/src/cpu/kernel/asm/rlp/read_to_memory.asm
evm/src/cpu/kernel/asm/transactions/router.asm

E.g. make sure the RLP segment is only used with the kernel context. Using current-context memory would also work, we just need to be consistent.
For transaction parsing etc, the context should be 0 anyway, but explicitly referring to kernel memory feels more idiomatic to me.

Switch a few uses of current-context memory to kernel memory

---

evm/src/arithmetic/arithmetic_stark.rs
evm/src/arithmetic/columns.rs
evm/src/arithmetic/modular.rs
evm/src/arithmetic/utils.rs

Implementation of the **non-standard** `SUBMOD` instruction in the arithmetic table.
Does the obvious thing: `SUBMOD(a, b, m) := (a - b) % m`, except that the result is always in the range `[0, m)`. (Cf. typical definitions of `%` which produce a negative result if `a-b` is negative.)

Implement SUBMOD instruction

---

evm/src/arithmetic/arithmetic_stark.rs
evm/src/arithmetic/columns.rs
evm/src/arithmetic/modular.rs

Implements the `DIV` instruction in terms of the `MOD` instruction.
The only real complication is handling the standard's definition that division by zero is zero. With `MOD` we can obtain the correct answer by forcing the modulus to be zero, whereas with `DIV` the modulus acts as the denominator and must be forced to be "`2^256`" to get the correct answer.

Implement DIV instruction

---

evm/src/cpu/kernel/asm/mpt/accounts.asm
evm/src/cpu/kernel/asm/mpt/storage/storage_write.asm

Unless I'm missing something, `ADDRESS` is not a native instruction

Use address macro instead of opcode

---

evm/src/cpu/kernel/interpreter.rs
evm/src/cpu/kernel/tests/curve_ops.rs
evm/src/cpu/kernel/tests/ecrecover.rs
evm/src/cpu/kernel/tests/exp.rs
evm/src/cpu/kernel/tests/fields.rs
evm/src/cpu/kernel/tests/hash.rs
evm/src/cpu/kernel/tests/ripemd.rs

Instead of passing around a kernel object.

Use static `KERNEL` in tests

---

evm/src/arithmetic/utils.rs
evm/src/cpu/columns/general.rs
evm/src/cpu/cpu_stark.rs
evm/src/cpu/kernel/aggregator.rs
evm/src/cpu/kernel/asm/main.asm
evm/src/cpu/kernel/asm/shift.asm
evm/src/cpu/mod.rs
evm/src/cpu/shift.rs
evm/src/memory/segments.rs

Code to verify shift left/right instructions on the EVM. Doesn't include generation code, that will come later once some upcoming changes from @nbgl are merged. I think the lack of generation code is probably the cause of the failing test. It is not currently connected to the arithmetic table, but that will be handled in a follow-up PR.

EVM shift left/right operations

---

evm/src/arithmetic/columns.rs
evm/src/arithmetic/compare.rs

We originally expected signed operations to be implemented in the arithmetic table, but as they are very very infrequently used, we have decided to implement them "in software" to save some arithmetic table columns. This PR removes the code and placeholders that were included prior to the decision to exclude these operations from the arithmetic table.

Remove signed operation code from arithmetic table

---

plonky2/src/fri/challenges.rs
plonky2/src/fri/prover.rs
plonky2/src/iop/challenger.rs

We don't think this is required for soundness, but just to remove any doubt.
Old protocol:
```
...
P sends final_poly
V samples random r
P sends pow_witness (not in transcript)
V computes pow_response = H(r, pow_witness)
V asserts pow_response has N leading 0s
...
```
Updated protocol:
```
...
P sends final_poly
P sends pow_witness
V samples random pow_response
V asserts pow_response has N leading 0s
...
```
The updated protocol is arguably simpler, at least for the verifier. For the prover, doing the search efficiently becomes a bit harder, as we need a more compact encoding of the `Challenger` state to clone.
I did something similar to `Challenger::compact()`, but didn't want to use `compact()` itself, as we don't want to do the whole duplexing step until after we observe a particular …

Include the FRI prover's PoW witness in the transcript

---

field/src/lib.rs

Current `main` fails to compile with the the standard "fast compilation" flags: 
```
RUSTFLAGS='-C target-cpu=native' cargo test --release
```
It complains that `#![feature(stdsimd)]` is missing.
Not sure how this got in to main, but it's recent; maybe from the `no-std` PR?

Add missing feature to field crate

---

plonky2/src/plonk/proof.rs
plonky2/src/util/serialization.rs

Followup to #806.
A few goals here
- Zero dependencies on std.
- Provide a single (memory buffering) impl of `Write` to make sure there's no confusion.
- Move closer to the `std::io` APIs. Hopefully they will be available without std at some point (there have been some discussions...).
More specifically, this
- Changes `Buffer` to not use std's `Cursor`.
- Removes `impl Write` for `Buffer`, since it's implemented for `Vec<u8>`.
- Adds a concrete I/O error type to mimic `std::io`'s.
- Combines `Position` and `Size` into `Remaining`.

Serialization refactor

---

evm/src/cpu/kernel/asm/account_code.asm
evm/src/generation/prover_input.rs

So that it can be used to load code we're going to execute into the code segment of a certain context.

Make `load_code` a bit more general

---

.github/workflows/continuous-integration-workflow.yml

Needed until https://github.com/rust-lang/rust/issues/105037 is fixed.

Set CI to use an older version of nightly

---

plonky2/src/fri/proof.rs
plonky2/src/gadgets/polynomial.rs
plonky2/src/hash/hash_types.rs
plonky2/src/plonk/circuit_builder.rs
plonky2/src/plonk/proof.rs
plonky2/src/recursion/conditional_recursive_verifier.rs
plonky2/src/recursion/cyclic_recursion.rs
plonky2/src/recursion/dummy_circuit.rs
plonky2/src/recursion/mod.rs

- Have the caller to `cyclic_recursion` create and pass in the virtual proof
- Split `dummy_proof` into preprocessing and proving, so that we don't need to redo the preprocessing work in each `set_cyclic_recursion_data_target` call
- Have the caller update `num_public_inputs` instead of doing it in `cyclic_recursion`. This is a little less convenient but I think it's probably best to leave the caller's config untouched, following the principle of least surprise
- Have `set_cyclic_recursion_data_target` take a sparse set of public inputs. Taking some PIs with the lowest indices didn't seem very general. I still have some reservations about this part of the API - I think it would seem cleaner if PIs of a proof which wasn't selected for verification were simply ignored - but perhaps there …

Cyclic recursion tweaks

---

evm/src/arithmetic/add.rs
evm/src/arithmetic/arithmetic_stark.rs
evm/src/arithmetic/columns.rs
evm/src/arithmetic/compare.rs
evm/src/arithmetic/modular.rs
evm/src/arithmetic/sub.rs

Split verification of modular operations across two rows so that the arithmetic table is only 72 columns wide instead of 144 columns wide.
[[Fix explained below.]](https://github.com/mir-protocol/plonky2/pull/813#discussion_r1022339721)
~~NB: Test currently fails because of [this line](https://github.com/mir-protocol/plonky2/blob/e0d8fdd2f836ad3767e72b57bf04ee73938fe337/evm/src/arithmetic/modular.rs#L411):~~
```
yield_constr.constraint_last_row(filter);
```
~~I suspect this line is correct, but that I'm not building the `ConstraintConsumer` correctly in the tests. @nbgl Please advise?~~

Halve number of columns used by arithmetic table

---

evm/src/memory/memory_stark.rs
evm/src/witness/memory.rs

Previously we would pad the memory table until it's large enough to handle the largest range check that would occur. This seems suboptimal, but wasn't a major concern before. Now it's a more pressing issue, because the CPU's uses memory lookups in its shift logic, and this could trigger memory reads with `virt` as high as 2^32 - 1. We wouldn't want to pad the memory table to 2^32, but luckily these gaps are still small enough that we can fill them with dummy reads, and will never need more than ~2^16 dummy reads in an unlikely worst case.

Add dummy reads to fill any large gaps in memory fields

---

evm/src/cpu/kernel/asm/core/transfer.asm
evm/src/cpu/kernel/interpreter.rs
evm/src/witness/memory.rs
evm/src/witness/operation.rs
evm/tests/transfer_to_new_addr.rs

It was creating a new account with the hash of an empty storage trie, when really it should be a pointer to an empty storage trie. We can use 0 as this pointer since `@SEGMENT_TRIE_DATA[0] = 0 = @MPT_NODE_EMPTY`.
Also a couple tweaks that helped me debug, like moving the memory value range checks from the interpreter into `MemoryState`, so they're done in actual witness generation as well as interpreter tests.

Fix to `add_eth`

---

evm/src/cpu/stack.rs

I think that's all we need for the JUMPDEST flag.

Constrain memory channels in JUMPDEST

---

evm/src/cpu/columns/general.rs
evm/src/cpu/cpu_stark.rs
evm/src/cpu/jumps.rs
evm/src/cpu/stack.rs
evm/src/util.rs
evm/src/witness/operation.rs

Also re-enables jump constraints, as now they pass the tests

Simplify `JUMP`/`JUMPI` constraints and finish witness generation

---

plonky2/src/gadgets/arithmetic.rs

This PR adds a "logical or" gadget for `BoolTarget`s.
I was writing some gadgets and found myself writing this over and over again and I thought it would be useful for others.

add `or` gadget for `BoolTarget`

---

evm/src/cross_table_lookup.rs
evm/src/fixed_recursive_verifier.rs
evm/src/get_challenges.rs
evm/src/lib.rs
evm/src/permutation.rs
evm/src/proof.rs
evm/src/prover.rs
evm/src/recursive_verifier.rs
evm/src/verifier.rs
evm/tests/empty_txn_list.rs
evm/tests/transfer_to_new_addr.rs
plonky2/examples/bench_recursion.rs
plonky2/src/gadgets/random_access.rs
plonky2/src/hash/merkle_proofs.rs
plonky2/src/hash/merkle_tree.rs
plonky2/src/iop/witness.rs
plonky2/src/plonk/circuit_builder.rs
plonky2/src/plonk/circuit_data.rs
plonky2/src/recursion/conditional_recursive_verifier.rs
plonky2/src/recursion/cyclic_recursion.rs
plonky2/src/recursion/dummy_circuit.rs
plonky2/src/recursion/recursive_verifier.rs

The goal here is to end up with a single "root" circuit representing any EVM proof. I.e. it must verify each STARK, but be general enough to work with any combination of STARK sizes (within some range of sizes that we chose to support). This root circuit can then be plugged into our aggregation circuit.
In particular, for each STARK, and for each initial `degree_bits` (within a range that we choose to support), this adds a "shrinking chain" of circuits. Such a chain shrinks a STARK proof from that initial `degree_bits` down to a constant, `THRESHOLD_DEGREE_BITS`.
The root circuit then combines these shrunk-to-constant proofs for each table. It's similar to `RecursiveAllProof::verify_circuit`; I adapted the code from there and I think we can remove it after. The main difference is that now …

Shrink STARK proofs to a constant degree

---

plonky2/src/fri/oracle.rs
plonky2/src/fri/recursive_verifier.rs
plonky2/src/fri/verifier.rs

Reverts the degree adjustment part of #436. As @jimpo pointed out, the adjustment complicates security by allowing rational functions of the form `poly(x) / x`.
In hindsight a tight degree bound shouldn't be necessary. Ultimately we want to check that some witness function `f(x)` exists satisfying (simplified) `c(f(x)) = Z_H(x) q(x)`.  We only need `f(x)` to be low-degree because that allows us to use polynomial identity testing. With PIT we don't care about exact degree bounds; a negligible degree change will have a negligible effect on PIT soundness.

Allow non-tight degree bound

---

evm/src/proof.rs
evm/src/recursive_verifier.rs

Some logic was replaced by the constant-degree logic in `fixed_recursive_verifier`.

Remove some older EVM recursion logic

---

evm/src/fixed_recursive_verifier.rs
evm/tests/empty_txn_list.rs

Which can be used to compress two proofs into one. Each inner proof can be either
- an "EVM root" proof (which typically proves one transaction, though it could be 0 or more)
- another aggregation proof

Add aggregation circuit

---

evm/src/cpu/kernel/asm/curve/bn254/curve_add.asm
evm/src/cpu/kernel/asm/curve/bn254/curve_mul.asm
evm/src/cpu/kernel/asm/curve/bn254/msm.asm
evm/src/cpu/kernel/asm/curve/bn254/precomputation.asm
evm/src/cpu/kernel/asm/curve/common.asm
evm/src/cpu/kernel/asm/curve/secp256k1/curve_add.asm
evm/src/cpu/kernel/asm/curve/secp256k1/ecrecover.asm
evm/src/cpu/kernel/asm/curve/secp256k1/precomputation.asm
evm/src/cpu/kernel/tests/ecc/curve_ops.rs

No functional changes, just using a more consistent naming schemes for elliptic curve ASM functions.

ECC ASM functions renaming

---

plonky2/src/gadgets/split_base.rs

Methods like split_le are public. le_sum is the inverse map so useful to have it pub as well (at the very least, we’d like to access it).

Make le_sum public

---

plonky2/Cargo.toml

Compiling plonky2 for `wasm32-unknown-unknown` currently fails.
Steps to reproduce:
- `rustup update nightly`
- `rustup target add wasm32-unknown-unknown --toolchain nightly`
- `cargo +nightly build --no-default-features --target wasm32-unknown-unknown --manifest-path plonky2/Cargo.toml`
(Note that the whole workspace cannot be compiled to `wasm32-unknown-unknown` because of the hardcoded jemalloc specification in `evm` crate).
The issue is a common one arising when dealing with `rand_core` related crates. Specifying the `getrandom` dependency with the feature "js" enabled when compiling to wasm does the trick.

Fix plonky2 compilation with wasm32-unknown-unknown target

---

field/src/field_testing.rs
field/src/goldilocks_field.rs
plonky2/src/hash/poseidon_goldilocks.rs

This PR overrides the default MDS layer implementation of Poseidon on x86 targets to perform an FFT-based matrix-vector multiplication, similarly to what is done on aarch64 targets. Given that the x86_64-specific methods for Poseidon are all disabled, this can yield a significant speed-up on such targets, compared to the naive `mds_row_shf` implementation.
On Ubuntu 22.04, Intel® Core™ i7-9750H CPU @ 2.60GHz × 12, I am getting a 30% speed-up when running the `hashing` benchmark.

Add FFT-based specification for Poseidon MDS layer on x86 targets

---

evm/src/witness/errors.rs
evm/src/witness/memory.rs
evm/src/witness/operation.rs

A few tests currently panic with a `virt too large` error.

Return error instead of panic in memory operation

---

evm/src/cpu/kernel/asm/signed.asm

Syscalls expect the kernel return info to be at the top of the stack.

Fix signed syscalls stack

---

evm/src/cpu/kernel/aggregator.rs
evm/src/cpu/kernel/asm/mpt/hash/hash_trie_specific.asm
evm/src/cpu/kernel/asm/rlp/encode.asm
evm/src/cpu/kernel/asm/rlp/encode_rlp_scalar.asm

Doubly RLP-encode storage values

---

evm/src/cpu/kernel/asm/account_code.asm
evm/src/cpu/kernel/asm/memory/memcpy.asm
evm/src/cpu/kernel/asm/memory/syscalls.asm

The `offset` parameter in the *COPY opcodes can be arbitrarily large, leading to an error when trying to access memory directly. Fixed by adding a check for large offsets.

Fix copy opcodes when offset is large

---

evm/src/cpu/kernel/asm/core/create.asm

Fixes the crash due to a huge allocation in `returndatacopyPythonBug_Tue_03_48_41-1432`.

Fix `run_constructor`

---

evm/Cargo.toml
evm/src/fixed_recursive_verifier.rs

This PR fixes the `prove_block()` method of `AllRecursiveCircuits`.

Fix BlockCircuitData proofs

---

evm/src/cpu/kernel/asm/core/call.asm

Finish implementations of `sys_delegatecall, sys_staticcall, sys_callcode`. Mostly copy-pasted from `sys_call`.

Implement rest of *CALL opcodes

---

evm/src/cpu/kernel/asm/core/call.asm

Have to take the minimum with returndata size.

Fix `copy_returndata_to_mem`

---

evm/src/cpu/cpu_stark.rs
evm/src/cpu/stack.rs

Makes stack constraints pass by changing the shift left/right behaviors such that `disable_other_channels = false` (those channels are already constrained in `shift.rs`). It also sets the number of pops of `BASIC_TERNARY_OP` to 3.

Enable stack constraints

---

Cargo.toml

Since it's a library, in practice release builds are used for slower tests, not for a binary that needs to be reproducible.

Incremental release builds

---

plonky2/examples/bench_recursion.rs
plonky2/src/lib.rs

Pull request #873 introduced the use of the incomplete `generic_const_exprs` feature ([here](https://github.com/mir-protocol/plonky2/pull/873/files#diff-ab60f6df9f439d7609ceba5ffaa210cfdee8e1c25fae13c3e2c799e0b3c92d04R4)) but did not disable the compiler warning for it, which seems to have been causing CI failures on main and branches since. This PR disables the warning for incomplete features in Plonky2.

Fix generic const expressions warning

---

evm/Cargo.toml
evm/src/cpu/kernel/assembler.rs
evm/src/generation/prover_input.rs

Introduces methods for serializing / deserializing the Kernel.
Given the time it takes to bootstrap now with the introduction of the precompile files from #983 (>100sec on my machine), it may come in handy to skip the process when working on other parts of the crate.

Provide methods for serializing Kernel

---

evm/src/cpu/kernel/asm/core/precompiles/rip160.asm
evm/src/cpu/kernel/asm/core/precompiles/sha256.asm

Replace `%stack` calls with equivalent opcodes.
The sequence of opcodes was actually generated by the `%stack` macro expander function, then substituted in at the call site.

Fix precompile (and hence testing) slowdown

---

.github/workflows/continuous-integration-workflow.yml

Only print warning or errors from the log.
The CI currently produces about 0.4GiB of data every single run, the vast majority of it empty or useless debug messages.

Quieter continuous integration

---

evm/src/cpu/kernel/asm/core/access_lists.asm
evm/src/cpu/kernel/asm/mpt/storage/storage_read.asm
evm/src/cpu/kernel/asm/mpt/storage/storage_write.asm
evm/src/cpu/kernel/tests/core/access_lists.rs

Implement gas calculation for SSTORE. 
Works by storing the value in the storage keys access list. That way, the original value (i.e. value before the tx) of a storage slots is stored there and can be used in the gas calculation.
This is rather hacky, so it should probably be redesigned at some point, but in the meantime it helps filtering out tests that fail because of gas miscalculations.

SSTORE gas

---

plonky2/examples/fibonacci_serialization.rs
plonky2/src/fri/proof.rs
plonky2/src/plonk/proof.rs

Instead, ProofChallenges should be generated in the verifier (e.g. the gnark plonky2 verifier)

remove ProofChallenges serialization

---

evm/src/cpu/bootstrap_kernel.rs

Fix todo related to constraining memory channels to be disabled at the end of kernel bootstrapping.

Constrain memory channels at end of bootstrapping

---

field/src/arch/x86_64/avx2_goldilocks_field.rs
field/src/arch/x86_64/avx512_goldilocks_field.rs
field/src/lib.rs
field/src/packed.rs

Like it says on the tin. Turns out the only functions using `generic_const_exprs` were `PackedField::as/from_arr()`, which were only called in the test suite. Removed those functions and replaced with the slice equivalents.

Remove `generic_const_exprs` dependency from field crate

---

evm/Cargo.toml
evm/src/cpu/kernel/asm/core/precompiles/rip160.asm
evm/src/cpu/kernel/asm/core/precompiles/sha256.asm
evm/src/cpu/kernel/asm/hash/ripemd/update.asm
evm/src/cpu/kernel/asm/memory/core.asm

#1029 broke some sha2 and ripemd EVM tests, this fixes them! (I think, I couldn't run the biggest tests on my machine)

Fix to hash precompile so EVM tests pass

---

evm/src/generation/mod.rs
evm/src/generation/mpt.rs
evm/tests/add11_yml.rs
evm/tests/self_balance_gas_cost.rs

Slightly easier for us if we use `H256` instead of `H160`.

`TrieInputs` now uses `H256` for storage account addresses

---

evm/src/arithmetic/arithmetic_stark.rs

The current padding only applies up to 65536 rows. For some ethereum tests of the test suite (for instance `GeneralStateTests/stSpecialTest/deploymentError`), the ArithmeticStark trace becomes larger and a panic arises.
This handles proper padding in those cases.

Fix arithmetic stark padding

---

evm/src/witness/operation.rs

The `U256` type computes Shr/Shl by calling the `as_usize` method, which panics if the value is larger than `usize::max_value()`.

Prevent shift ops from panicking

---

evm/src/cpu/kernel/asm/core/create_contract_account.asm

Caused a bug when creating an account with non-empty storage. See `stSpecialTest/FailedCreateRevertsDeletion`.

Don't overwrite existing account

---

evm/src/cpu/kernel/asm/journal/account_loaded.asm
evm/src/cpu/kernel/asm/journal/account_touched.asm

Yet another weird Ethereum quirk

RIPEMD doesn't get untouched

---

evm/src/cpu/columns/general.rs
evm/src/cpu/cpu_stark.rs
evm/src/cpu/jumps.rs
evm/src/cpu/stack.rs
evm/src/cpu/stack_bounds.rs
evm/src/witness/errors.rs
evm/src/witness/operation.rs
evm/src/witness/transition.rs

@dlubarov, you were right. I should have done this the simpler way to begin with…
This PR simplifies stack bounds (overflow/underflow) constraints. `POP` is finally constrained.
(Also, a few misc. witness generation panic->exception stuff that's unrelated but I was already touching that code.)

Simplify stack bounds constraints

---

evm/src/cpu/kernel/asm/core/create.asm
evm/src/cpu/kernel/asm/core/terminate.asm
evm/src/cpu/kernel/asm/core/transfer.asm
evm/src/cpu/kernel/asm/journal/storage_change.asm
evm/src/cpu/kernel/asm/mpt/accounts.asm
evm/src/cpu/kernel/asm/mpt/delete/delete.asm
evm/src/cpu/kernel/asm/mpt/insert/insert.asm
evm/src/cpu/kernel/asm/mpt/storage/storage_write.asm
evm/src/memory/segments.rs
evm/src/prover.rs

With the journal-based approach to state reversion, we don't need the tries to be copy-on-write.
MPT insertion and deletion can also be optimized a lot by removing the copying logic. Left that as a TODO.

Remove parts of the copy-on-write logic

---

plonky2/examples/bench_recursion.rs
plonky2/src/gadgets/lookup.rs
plonky2/src/gadgets/mod.rs
plonky2/src/gates/gate.rs
plonky2/src/gates/lookup.rs
plonky2/src/gates/lookup_table.rs
plonky2/src/gates/mod.rs
plonky2/src/gates/selectors.rs
plonky2/src/lib.rs
plonky2/src/lookup_test.rs
plonky2/src/plonk/circuit_builder.rs
plonky2/src/plonk/circuit_data.rs
plonky2/src/plonk/get_challenges.rs
plonky2/src/plonk/proof.rs
plonky2/src/plonk/prover.rs
plonky2/src/plonk/validate_shape.rs
plonky2/src/plonk/vanishing_poly.rs
plonky2/src/plonk/verifier.rs
plonky2/src/recursion/conditional_recursive_verifier.rs
plonky2/src/recursion/recursive_verifier.rs
plonky2/src/util/serialization/gate_serialization.rs
plonky2/src/util/serialization/generator_serialization.rs
plonky2/src/util/serialization/mod.rs

We introduce an implementation for lookups on the Plonk side. We make use of the logarithmic derivatives construction of [Ulrich Haböck](https://eprint.iacr.org/2022/1530), and followed rather closely the [Tip5](https://eprint.iacr.org/2023/107) implementation.
If no lookups are used, then no overhead is incurred.
If you do want to use lookups, here's a simple example:
```rust
// Table taken from the Tip5 S S-Box
let lut_outputs = vec![
0, 7, 26, 63, 124, 215, 85, 254, 214, 228, 45, 185, 140, 173, 33, 240, 29, 177, 176,
32, 8, 110, 87, 202, 204, 99, 150, 106, 230, 14, 235, 128, 213, 239, 212, 138, 23, 130,
208, 6, 44, 71, 93, 116, 146, 189, 251, 81, 199, 97, 38, 28, 73, 179, 95, 84, 152, 48,
35, 119, 49, 88, 242, 3, 148, 169, 72, 120, 62, 161, 166, 83, 175, 191, 137, 19, 100,
129, 112, …
```

Implement lookups with logarithmic derivatives in Plonk

---

.github/workflows/continuous-integration-workflow.yml

The latest nightly toolchain broke the build, see #1110. This PR fixes the toolchain version to 2023-06-30 until new versions work.

Fix nightly version in CI to 2023-06-30

---

evm/src/cpu/gas.rs
evm/src/cpu/kernel/tests/bignum/mod.rs
evm/src/cpu/memio.rs
evm/src/cpu/stack.rs
evm/src/recursive_verifier.rs
field/Cargo.toml
plonky2/Cargo.toml
plonky2/src/fri/prover.rs
plonky2/src/gates/selectors.rs
plonky2/src/iop/challenger.rs
starky/Cargo.toml

Fixes for updated clippy. Mostly following its suggestions, except for two kinds of errors where it's wrong about arguments to the `izip!` macro (I bumped the itertools version, but seems like it hasn't been updated); so in those cases I just use an `allow`

clippy fixes

---

evm/src/cpu/gas.rs
evm/src/cpu/kernel/tests/bignum/mod.rs
evm/src/cpu/memio.rs
evm/src/cpu/stack.rs
evm/src/recursive_verifier.rs
field/Cargo.toml
plonky2/Cargo.toml
plonky2/src/fri/prover.rs
plonky2/src/gates/selectors.rs
plonky2/src/iop/challenger.rs
starky/Cargo.toml

Reverts mir-protocol/plonky2#1109
Since we moved to a prior nightly in mir-protocol/plonky2#1113, these "fixes" actually broke it
We can re-apply the fixes from 1109 after the new nightly's issues are resolved and we move back to using it

Revert "clippy fixes"

---

evm/src/witness/operation.rs

We noticed in some tests with stack overflows that the macro `set_length` caused `context_ops` constraints to fail, due to the `SET_CONTEXT` instruction.
In the case where the context does not change (which is the case for `set_length`), there is a `MemoryOp` to read the stack length, but the memory channels are not set. The failing constraints concerned the said unset memory channel. Thus, this PR sets the memory channels in that case.

Fix generate_set_context

---

evm/src/witness/operation.rs

We noticed that some proof verifications were failing due to a constraint in `jump.rs`: `lv.op.jump * (cond[0] - P::ONES)` (l. 76). 
This is due to the fact that in `generate_jump`, `row.mem_channels[1].value[0]` was only set to 1 if it was a kernel operation. However, the comment in `jump.rs` explains that `row.mem_channels[1].value[0]` is a predicate that is always 1 when the operation is a `JUMP`.
We therefore set the memory value to 1 outside of the `if` condition in `generate_jump`.

Fix jump operation generation

---

evm/src/fixed_recursive_verifier.rs
plonky2/src/plonk/circuit_data.rs
plonky2/src/plonk/proof.rs
plonky2/src/recursion/cyclic_recursion.rs
plonky2/src/util/serialization/mod.rs

Deserializing (especially large objects like `AllRecursiveCircuits`)  can get expensive when copying the bytes into a new `Buffer`.
Also removes the conditional attribute with `std` (I'm not sure why it was to begin with, as `Vec` is imported from `alloc`?).

Make serializer work with slices

---

evm/src/fixed_recursive_verifier.rs
evm/tests/empty_txn_list.rs
plonky2/src/gates/constant.rs

Tiny tweak to remove the need for matching start ranges in the `AllRecursiveCircuits` initialization. Allows to scrap out ~4.6GB of useless data when serializing (out of the ~6.5GB for the empty_txn_list example, i.e.  ~72% reduction).
Also fixes some invalid end ranges.

Remove need for matching start ranges

---

field/src/arch/x86_64/avx2_goldilocks_field.rs

PR #1092 moved some methods from `Field64` to `Field` but didn't update the imports in arch files.

Fix import in arch tests

---

evm/src/generation/prover_input.rs

The modulus in prover_inputs `run_bignum_modmul()` is not being checked to be different than zero, resulting in a panic in several tests from the EVM suite (see for instance `modexpTests` case variants 4, 5, 8, 25, 31, 40, 41, 51, 101.

Fix risk of division by zero

---

evm/src/generation/prover_input.rs

We noticed that some tests related to `modexp_bignum` were failing in evm-tests with a KernelPanic (such as `modexpTests_62` and `modexpTests_65`, [here](https://github.com/ethereum/tests/blob/0902578614503cb52e9b115f8714a17c39787c58/src/GeneralStateTestsFiller/stPreCompiledContracts/modexpTestsFiller.yml#L4)). 
This was due to the fact that the context used in the ASM code and the one used in `bignum_modmul`, in prover_input.rs, were inconsistent. This PR changes, in `bignum_modmul`, `&self.memory.contexts[0]` into `self.memory.contexts[n - 1]` where `n = self.memory.contexts.len()` to make the tests pass.

Change context used in `bignum_modmul`

---

evm/src/arithmetic/byte.rs

`hi_limb_sum` initial value when evaluating `byte` constraints seems to not be set correctly, which sometimes makes the constraint `yield_constr.constraint(is_byte * (hi_limb_sum * hi_limb_sum_inv - idx_is_large));` fail.
This is visible for instance with test vectors `randomStatetest142` / `randomStatetest143` / `randomStatetest185` in [tests](https://github.com/ethereum/tests/tree/develop)/[GeneralStateTests/stRandom](https://github.com/ethereum/tests/tree/develop/GeneralStateTests/stRandom)

Fix failing byte constraint

---

plonky2/Cargo.toml

building `plonky2` currently fails:
```console
$ cd plonky2 && cargo build
--> plonky2/src/plonk/circuit_data.rs:348:39
... the trait `Serialize` is not implemented for `Arc<Vec<(u16, u16)>>`
```
We have to enable `rc` feature in `serde`.
Note that this fix is also present in #1114

deps(serde): use `rc` feature in `plonky2` crate

---

.github/workflows/continuous-integration-workflow.yml

CI now runs `cargo check` for each of the `plonky2`, `starky`, and `evm` subdirectories. This allows us to check compiling individual crates separately, which sometimes fails when compiling the whole workspace succeeds (because of feature-related issues), brought up in #1138
It seems like GitHub Actions can't actually run commands from path other than root, so this uses the workaround of specifying their `Cargo.toml` as a manifest — see [here](https://github.com/actions-rs/cargo/issues/86#issuecomment-667088617). But in our case I think it's the same thing
I checked that this indeed causes CI to fail prior to #1138's changes

CI: build in subdirectories

---

plonky2/Cargo.toml

I have been having an issue with building the latest version on a Mac M2 Max. 
The compiler was throwing some messages regarding the itertools crate. I found that adding the "use_std" features of the itertools flag (only under the "std" feature of course) solves this problem for me.

Build issues on Mac M2: add "Itertools/use_std" flag to "std" 

---

plonky2/Cargo.toml
plonky2/src/plonk/prover.rs
plonky2/src/plonk/vanishing_poly.rs

We've been using lookups downstream for a while, with tables of size 2^16 (for u16 range checks) and hundreds of thousands of lookups in a circuit. This PR addresses the main bottlenecks that were at first producing poor building/proving times (around 100x/3x overall vs. baseline, respectively) at this scale.
Changes: 
- using a linear-time pass to count multiplicities vs. the current O(n^2) implementation
- precomputing the RE poly evaluations, which were being re-computed redundantly. This sped up the [`compute quotient polys`](https://github.com/mir-protocol/plonky2/blob/main/plonky2/src/plonk/prover.rs#L229-L243) step of proving by about 10x for our circuits (size 2^21 with width ~200, using the aforementioned size 2^16 tables)
The remaining significant bottleneck we encountered was …

Lookup arg optimizations

---

plonky2/src/gadgets/lookup.rs
plonky2/src/gates/lookup_table.rs
plonky2/src/lookup_test.rs
plonky2/src/plonk/circuit_builder.rs

@npwardberkeley Another tiny lookup-related PR, just to fix a wrong naming in `LookupTableGate` id, and to remove the second condition in an assertion check.
More specifically, the second condition (`lut_index >= self.get_luts_length()`) in the OR should first be corrected to `lut_index < self.get_luts_length()`. It wasn't caught in unit tests because we were always satisfying the first condition. Secondly, because the `luts` and `lut_to_lookups` are necessarily of the same size, we can't have `lut_index` being greater than the latter (indeed, the only way for it to fail would be for a user to call `add_lookup_from_index()` with an invalid index when designing the circuit, which would be caught prior to reaching `add_all_lookups()`.
Related to this, I added two additional unit tests, to …

Lookup check

---

evm/src/memory/columns.rs

A minor oversight in c38a98f left five unused columns in the memory table. This tiny PR cuts the number of columns in the memory table from 26 to 21 (not including CTL).

Cut 5 Columns From The Memory Table With This One Weird Trick!

---

evm/src/all_stark.rs
evm/src/cpu/bootstrap_kernel.rs
evm/src/cpu/kernel/assembler.rs
evm/src/cross_table_lookup.rs
evm/src/fixed_recursive_verifier.rs
evm/src/generation/mod.rs
evm/src/keccak_sponge/columns.rs
evm/src/keccak_sponge/keccak_sponge_stark.rs
evm/src/permutation.rs
evm/src/proof.rs
evm/src/recursive_verifier.rs
evm/src/util.rs
evm/src/verifier.rs
evm/src/witness/operation.rs
evm/tests/empty_txn_list.rs
plonky2/src/plonk/circuit_builder.rs

This pull request fixes the memory CTL so that it doesn't have to be disabled anymore.
It also introduces a verifier-only memory bus to check a small set of memory operations.
Related issue: https://github.com/mir-protocol/plonky2/issues/1004
In the `KeccakSponge` STARK, the output of the hash is stored in `u32` columns written in big endian format. This introduces a discrepancy with how the columns are written in the `Memory` STARK, and makes the CTL check fail. The easiest solution to implement we found was to add columns in `KeccakSponge` for individual bytes of the output, which can be recombined in little endian format.
Following Daniel's advice [here](https://github.com/mir-protocol/plonky2/issues/988#issuecomment-1512002282), we introduced a set of memory operations which can be …

Fix the memory CTL and implement the verifier memory bus

---

plonky2/src/util/mod.rs

So that it also works with eg `u64`, not just with field elements.

Generalise transpose

---

field/src/arch/x86_64/avx512_goldilocks_field.rs

PR #1092 introduced some compile errors in the architecture-specific testing code for fields. Some of these errors were fixed in #1134. The remainder of the errors are fixed in this PR.

Fix trait import in AVX512 tests

---

evm/src/fixed_recursive_verifier.rs
evm/src/recursive_verifier.rs
evm/src/util.rs

This PR fixes an issue introduced by #1026. This wasn't detected as the only usage of `AllRecursiveCircuits` is done with an empty transaction list.
To reproduce it, you can pass the inputs of the `simple_transfer` test to `prove_root()`. You will need to manually alter the `block_gas_limit` field (see below).
Changes:
- fix the endianess of the block beneficiary
- set all other `block_metadata` targets from the first limb of their `U256` counterpart, converted to a u32. This is a safety measure as each should be fitting in 32 bits by design (we're only considering their first limb). Otherwise testing for instance the `simple_transfer` inputs will fail with inconsistent `Target` value.
@npwardberkeley Would you mind reviewing the changes? As you were the one assigned to #1026 you're …

Fix prove_root()

---

plonky2/src/hash/poseidon_goldilocks.rs

The MDS layer implementation for x86-64 targets is moved inside a dedicated submodule to silence cargo warnings of dead code (at least until assembly optimizations for x86 targets are re-enabled).

Silence Poseidon warnings for ARM targets

---

evm/src/fixed_recursive_verifier.rs

If the prover is missing a preprocessed circuit when recursively verifying the initial transaction `AllProof` in `prove_root`, it will currently `panic!`. This change allows the prover to gently return early with an `Error`.

Error instead of panicking for missing preprocessed circuits

---

evm/src/witness/operation.rs

This PR sets the exception flag to 1 in `generate_exception`.

Set exception flag to 1.

---

evm/src/cpu/kernel/asm/main.asm
evm/src/fixed_recursive_verifier.rs
evm/src/generation/mod.rs
evm/src/proof.rs
evm/src/recursive_verifier.rs
evm/src/util.rs
evm/src/verifier.rs
evm/tests/add11_yml.rs
evm/tests/basic_smart_contract.rs
evm/tests/empty_txn_list.rs
evm/tests/self_balance_gas_cost.rs
evm/tests/simple_transfer.rs

See #1164 for discussion.
NB: This PR breaks the EVM test runner. Will open a PR to fix the runner once this is merged.

Write trie roots to memory before kernel bootstrapping 

---

evm/src/all_stark.rs
evm/src/cpu/cpu_stark.rs
evm/src/cpu/shift.rs
evm/src/witness/operation.rs

This PR addresses a point in https://github.com/mir-protocol/plonky2/issues/1150.
@unzvfu would you mind reviewing this PR, as you implemented the related operations?
Upon difficulties in getting the Arithmetic CTL to work, I realized (unless I missed something obvious) that we were not logging the corresponding MUL/DIV arithmetic operations when performing a shift.
I also updated the comment on the memory mapping, as I believe it is erroneous. We instead have
```
- mem_channel 0: shift
- mem_channel 1: value to be shifted (was referred as channel 0 previously)
- mem_channel 2: 2^shift
- mem_channel 5 (last): result
```
Let me know if I misunderstood anything! 🙏🏼

Connect SHL/SHR operations to the Arithmetic table

---

plonky2/src/gates/gate.rs

We need this field to be public. In order to be able to use a custom gate serializer. Cause else impl_gate_serializer! throws
`field `0` of `GateRef` is private` compilation error

Make field `0` of `GateRef` is private

---

evm/src/fixed_recursive_verifier.rs
evm/src/keccak_sponge/keccak_sponge_stark.rs
evm/src/verifier.rs
field/src/types.rs
plonky2/src/fri/proof.rs
plonky2/src/fri/prover.rs
plonky2/src/fri/recursive_verifier.rs
plonky2/src/gates/arithmetic_base.rs
plonky2/src/gates/arithmetic_extension.rs
plonky2/src/gates/exponentiation.rs
plonky2/src/gates/multiplication_extension.rs
plonky2/src/hash/keccak.rs
plonky2/src/plonk/permutation_argument.rs
plonky2/src/plonk/prover.rs
plonky2/src/plonk/vanishing_poly.rs
plonky2/src/util/partial_products.rs

Replaces some empty Vec / HashMap initializations with `with_capacity` to reduce the number of reallocations. Given than an empty vec will reallocate to a capacity of 4 directly on the first push, some tiny vecs are left untouched.
The number of reallocations can be evaluated with an external crate like [alloc_counter](https://docs.rs/alloc_counter/latest/alloc_counter/). Testing against `bench_recursion` example, i.e. replacing the `prove` calls with the code below
```rust
let mut timing = TimingTree::new("prove", Level::Debug);
let ((_, realloc, _), proof) =
count_alloc(|| prove::<F, C, D>(&data.prover_only, &data.common, pw, &mut timing).unwrap());
timing.print();
println!("Reallocations for proving: {:?}", realloc);
````
for both the initial dummy proof and the two recursive layers, a …

Reduce reallocations

---

evm/src/cpu/columns/mod.rs
evm/src/cpu/columns/ops.rs
evm/src/cpu/control_flow.rs
evm/src/cpu/cpu_stark.rs
evm/src/cpu/decode.rs
evm/src/cpu/dup_swap.rs
evm/src/cpu/gas.rs
evm/src/cpu/membus.rs
evm/src/cpu/modfp254.rs
evm/src/cpu/simple_logic/not.rs
evm/src/cpu/stack.rs
evm/src/cpu/stack_bounds.rs
evm/src/witness/transition.rs

Removes the `is_cpu_cycle` flag and replaces it by the sum of all operation flags when necessary.

Remove is_cpu_cycle

---

evm/src/cpu/bootstrap_kernel.rs
evm/src/cpu/columns/mod.rs

Now that CPU cycles are identified by the sum of the `op` instruction flags, we can do the same for the kernel bootstrapping flag, which are exactly the rows that are not CPU cycles.

Remove is_bootstrap_kernel column

---

evm/tests/add11_yml.rs
evm/tests/basic_smart_contract.rs
evm/tests/self_balance_gas_cost.rs
evm/tests/simple_transfer.rs

Runs the non-recursive EVM integration tests with Keccak config instead of Poseidon (now `simple_transfer` / `add11_yml` take ~95 sec each compared to ~140 sec).
Regarding the config used in tests, we're almost always using the `PoseidonGoldilocksConfig`. Given that this one is already checked in recursion-related tests, we may want to switch all others to `KeccakGoldilocksConfig`, to speed-up the CI further?

CI Speed-up

---

evm/src/fixed_recursive_verifier.rs
evm/src/get_challenges.rs
evm/src/proof.rs
evm/src/recursive_verifier.rs

Allows `BlockBaseFee` to be greater than 32 bits, following discussion in #1193.
@wborgeaud: the actual changes are in the first commit. The second one deals with code duplication removal and moves the `get_memory_extra_looking_products_circuit` method to recursive_verifier.rs where I think it should belong (based on where the other "circuit-version" verification methods are implemented).

Use 2 limbs for BlockBaseFee

---

evm/src/cpu/kernel/asm/mpt/delete/delete.asm
evm/src/cpu/kernel/asm/mpt/delete/delete_branch.asm
evm/src/cpu/kernel/asm/mpt/delete/delete_extension.asm
evm/src/cpu/kernel/asm/mpt/insert/insert.asm
evm/src/cpu/kernel/asm/mpt/insert/insert_leaf.asm

This PR deals with removing the copy-on-write logic in MPT insertion and deletion, as mentioned in [this PR](https://github.com/mir-protocol/plonky2/pull/1096). 
When testing on `test_simple_transfer`, we observe a reduction of the number of rows in a couple of STARKs, from
`TraceCheckpoint { arithmetic_len: 10288, cpu_len: 77254, keccak_len: 463, keccak_sponge_len: 26, logic_len: 3347, memory_len: 467164 }` 
in main, to:
`TraceCheckpoint { arithmetic_len: 10288, cpu_len: 77108, keccak_len: 453, keccak_sponge_len: 26, logic_len: 3297, memory_len: 465103 }`
with this optimization.
Most of the time, when there was a change of node type, I left a new node creation as I feared using the same node pointer would lead to overwritten data while updating the node. (It was generally easier to do in …

Remove copy on write for mpt_insert and mpt_delete

---

evm/src/arithmetic/byte.rs
evm/src/cpu/decode.rs
evm/src/cpu/membus.rs
evm/src/cross_table_lookup.rs
evm/src/memory/memory_stark.rs

This PR amortizes a few constraints with `mul_add_extension`, and removes unnecessary filtering in over-constrained statements. 
I removed the TODO comment I had previously written in the decode module, as I thought the op flags were being individually binary constrained elsewhere which is not the case, hence the comment was erroneous.

Misc constraints

---

Cargo.toml
evm/src/cpu/kernel/tests/account_code.rs
evm/src/cpu/kernel/tests/balance.rs
evm/src/cpu/kernel/tests/mpt/delete.rs
evm/src/cpu/kernel/tests/mpt/insert.rs
evm/src/cpu/kernel/tests/mpt/mod.rs
evm/src/generation/mpt.rs
evm/src/generation/outputs.rs
evm/src/generation/trie_extractor.rs

There was an edge case uncovered by the prover scheduler where storage trie keys could be `260` bits long, and `eth_trie_utils` can only support `256` bit keys. `eth_trie_utils` was quickly patched to support longer keys, but the solution is temporary and a better one should be implemented before we publish a new `crates.io` version.
Previously I had a temporary branch in `plonky2` that switched `plonky2` to use this patch, but this isn't the best for reproducible builds over time (unless we want to keep the branch forever). It might be better to instead push the patch directly to `plonky2` and then later bump it again once we have a proper fix.

Patch `eth_trie_utils` to use a non crates-io version

---

evm/src/proof.rs

Needed by the prover scheduler.

Made `PublicValues` serializable

---

plonky2/src/iop/generator.rs

This PR makes `generate_partial_witness` available outside of the crate. This is useful for reading intermediate values in the witness and for debugging circuits.

feat: make generate_partial_witness available outside the crate

---

evm/tests/empty_txn_list.rs

It seems the CPU table length got a bump following #1097, but the `empty_txn_list` test (although ignored on the CI) didn't get updated. This fixes the minimal ranges with the new CPU size.

Update ranges in empty_txn_list

---

evm/src/cpu/kernel/asm/core/create_receipt.asm
evm/src/cpu/kernel/asm/mpt/hash/hash_trie_specific.asm
evm/src/cpu/kernel/asm/mpt/load/load_trie_specific.asm

This PR implements receipts for transactions of types 1 and 2: the encoding is `txn_type || RLP(receipt)` for transaction types 1 and 2, and `RLP(receipt)` for Legacy transactions.

Implement receipts of types 1 and 2

---

evm/src/cpu/kernel/asm/main.asm
evm/src/cpu/kernel/constants/global_metadata.rs
evm/src/fixed_recursive_verifier.rs
evm/src/generation/mod.rs
evm/src/generation/mpt.rs
evm/src/get_challenges.rs
evm/src/memory/segments.rs
evm/src/proof.rs
evm/src/recursive_verifier.rs
evm/src/util.rs
evm/src/verifier.rs
evm/tests/add11_yml.rs
evm/tests/basic_smart_contract.rs
evm/tests/empty_txn_list.rs
evm/tests/log_opcode.rs
evm/tests/self_balance_gas_cost.rs
evm/tests/simple_transfer.rs

This PR aims at implementing the missing public value links, especially for public values introduced by the receipts and logs [PR](https://github.com/mir-protocol/plonky2/pull/1097):
- It applies reads for the transaction numbers, the cumulative gas used and block bloom filters (before and after the current transaction).
- It initializes block bloom filters (it creates a segment for the block bloom filters instead of using `GlobalMetadata`, to avoid code duplication, since each bloom filter is comprised of eight 32-bits words).
- It adds links in aggregation and block proofs for `cum_gas_used`, `txn_number` and `block_filters`.
- It also links state trie roots between block proofs and ensures that transaction and receipt tries are empty at the beginning of a block.
Please let me know if …

Add missing links between public values

---

plonky2/src/iop/target.rs
plonky2/src/iop/wire.rs

This PR adds support for adding the Serialize and Deserialize macro to targets. It addresses issue #1197.
Implementing automatic serialization/deserialization allows for types composed of targets to also support serde serialization/deserialization. This means that a lot of the manual code written to serialize generator structs can be fully automated with serde.

feat: implement serde Serialize and Deserialize for Target

---

evm/src/keccak/columns.rs
evm/src/keccak/keccak_stark.rs
evm/src/keccak/round_flags.rs

This PR removes the filtering column of KeccakStark, and instead replaces it with the latest round register (i.e. `reg(NUM_ROUNDS - 1)`.
To do so, I modified the padding approach so that it doesn't trigger issues either in the CTL or in the `round_flags` consistency check.
Although the reduction in number of columns is only of ~0.04%, it allows to get down to 2480 columns, i.e. 1 less Poseidon permutation per leaf hashing 😄 
@npwardberkeley As you've been heavily involved in the Keccak impl, would you mind reviewing? Sorry for the double request! 🙏🏼

Remove filter column for KeccakStark

---

evm/src/generation/mod.rs
evm/src/witness/traces.rs

The current `TraceCheckpoint` used for logging info only displays the number of operations per STARK module.

Display actual trace lengths instead of number of ops

---

evm/src/cpu/kernel/asm/core/syscall_stubs.asm
evm/src/cpu/kernel/asm/memory/metadata.asm
evm/src/cpu/kernel/constants/global_metadata.rs
evm/src/cpu/kernel/tests/block_hash.rs
evm/src/cpu/kernel/tests/mod.rs
evm/src/fixed_recursive_verifier.rs
evm/src/generation/mod.rs
evm/src/generation/prover_input.rs
evm/src/get_challenges.rs
evm/src/memory/segments.rs
evm/src/proof.rs
evm/src/recursive_verifier.rs
evm/src/verifier.rs
evm/tests/add11_yml.rs
evm/tests/basic_smart_contract.rs
evm/tests/empty_txn_list.rs
evm/tests/log_opcode.rs
evm/tests/self_balance_gas_cost.rs
evm/tests/simple_transfer.rs

This PR implements the BLOCKHASH opcode, following @wborgeaud's second suggestion [in this issue](https://github.com/mir-protocol/plonky2/issues/1173). It includes links between proofs, a couple of unit tests and the challenger observing the additional public values (the previous and current block hashes).
closes #1173

Add blockhash opcode

---

evm/src/cpu/kernel/constants/exc_bitfields.rs
plonky2/src/fri/prover.rs
plonky2/src/iop/challenger.rs

There's one compiler error that's preventing us from building on the latest nightly, and I managed to resolve it by making a paremeter into a reference. I tried a few other things before resorting to using a reference (like `#![feature(const_precise_live_drops)]`), but I couldn't get it to compile. I *think* using a reference here should have no performance changes (since it's still a `const fn` at the end of the day), but let me know if there's a better way to fix this error.
For reference, the error was this:
```sh
error[E0493]: destructor of `[std::ops::RangeInclusive<u8>; N]` cannot be evaluated at compile-time
--> evm/src/cpu/kernel/constants/exc_bitfields.rs:7:53
|
7  | const fn u256_from_set_index_ranges<const N: usize>(ranges: [RangeInclusive<u8>; N]) -> U256 {
| …
```

Latest nightly fix

---

Cargo.toml
evm/Cargo.toml
field/Cargo.toml
plonky2/Cargo.toml
starky/Cargo.toml

- Previously refered to specific `crates.io` versions.
- Motivation for this is to allow external projects to be able use specific revisions of this repo. Without this, a `[patch]` section is almost always required in the external project in order to force the internal plonky2 sub-crates to the same version, an approach which comes with its own issues.

Now refers to sub-crates using paths (and removed `patch` section)

---

evm/src/cpu/kernel/asm/memory/packing.asm

Slight overlook from #1212, but swapping `offset` and `len` in the stack macro of `mstore_unpacking` removes one `SWAP` from the set of operations it expands to (5 `SWAP` + 2 `DUP` originally).

Swap ordering in stack macro

---

evm/src/keccak_sponge/columns.rs
evm/src/keccak_sponge/keccak_sponge_stark.rs

The current trace layout for `KeccakSpongeStark` contains the `updated_state` in u32s, as well as the `final_digest` in bytes. Those correspond to the first 8 limbs of the `updated_state` and can therefore be used to recompute the 32-bit limbs in the CTLs.

Remove redundant Keccak sponge cols

---

.github/workflows/continuous-integration-workflow.yml

Clippy seems to have a weird bug, known upstream, for which a temporary fix seems to be deactivating incremental compilation. It happened on all the recent branches that have been pushed, probably triggered by the nightly update overnight.
cc @BGluth as you could encounter it in what you're doing if the toolchain isn't fixed.

Update clippy in CI

---

plonky2/src/lib.rs
plonky2/src/lookup_test.rs

Removes a bunch of redundant imports, moves the conditional compilation at the module level, and make the module private.

Cleanup lookup_test module and reduce module visibility

---

evm/src/cpu/kernel/asm/memory/syscalls.asm

This PR reuses the byte packing / unpacking approach from #1212 for `MLOAD` and `MSTORE`.

Reuse new packing instructions for MLOAD and MSTORE

---

evm/src/cross_table_lookup.rs

Tiny mistake in `eval_table`.
Also we now allow multi-row filters (not used yet, but maybe in the future).

Fix eval_table, multi-row filters

---

plonky2/src/plonk/prover.rs

This PR refactors the `prove` method into `prove_with_partition_witness` and `prove`. This would allow flexibility for external crates such as [plonky2x](https://github.com/succinctlabs/succinctx/tree/main/plonky2x) to have their own witness generation logic.

refactor: separate witness generation in prove method

---

evm/src/fixed_recursive_verifier.rs

Update the ranges indices in `AllRecursiveCircuits` to match the ordering of the `Tables` enum for clarity.

Update ranges indices

---

evm/src/proof.rs

`BlockMetadata` / `ExtraBlockData` are fully undocumented for now, and some fields may be confusing at first reading, so adding some light documentation.

Add some doc for BlockMetadata / ExtraBlockData

---

evm/src/byte_packing/byte_packing_stark.rs
evm/src/byte_packing/columns.rs

This PR removes the `SEQUENCE_LEN` column from the `BytePackingStark` module, reusing the `get_active_position()` helper method to retrieve the sequence length (i.e. final position) when `SEQUENCE_END` is activated.
credits to @hratoanina for noticing this!

Remove SEQUENCE_LEN in BytePackingStark

---

evm/src/get_challenges.rs

We noticed the recursive proofs were failing because the challenges were observed in the a different order in the recursive and non-recursive versions. This PR fixes the issue.

Fix observe_block_metadata

---

evm/src/cpu/kernel/interpreter.rs
evm/src/cpu/kernel/tests/account_code.rs
evm/src/cpu/kernel/tests/balance.rs
evm/src/cpu/kernel/tests/mpt/delete.rs
evm/src/cpu/kernel/tests/mpt/hash.rs
evm/src/cpu/kernel/tests/mpt/insert.rs
evm/src/cpu/kernel/tests/mpt/load.rs
evm/src/cpu/kernel/tests/mpt/read.rs
evm/src/cpu/kernel/tests/receipt.rs
evm/src/generation/mod.rs
evm/src/generation/mpt.rs
evm/src/generation/outputs.rs
evm/src/generation/prover_input.rs
evm/src/generation/state.rs
evm/src/generation/trie_extractor.rs
evm/src/prover.rs
evm/src/recursive_verifier.rs
evm/src/util.rs
evm/src/witness/errors.rs
evm/src/witness/memory.rs
evm/src/witness/operation.rs
evm/src/witness/util.rs

This PR partly addresses #1247. More specifically, it handles (on the EVM crate):
- all risky `as_usize()` calls
- all risky `expect()` calls
- `U256` methods with implicit internal panic (`from_big_endian` / `from_big_endian` / `div_mod`).
I haven't changed (unless required from cascade changes) the kernel / tests + interpreter files as those don't matter as much (panic in testing is fine, and the kernel risks of panic would arise during the offline preprocessing phase which would be caught ahead).

Handle additional panics

---

evm/src/generation/mpt.rs
evm/tests/log_opcode.rs

Needed for upgrading evm-tests runner.

Add type 1 and 2 txn for RLP encoding support

---

plonky2/src/gadgets/lookup.rs
plonky2/src/lookup_test.rs

This PR optimizes the instantiation of `LookupGate` and `LookupTableGate` instances when building a circuit. The optimization seems to be particularly effective on big lookup tables (e.g., with 2^16 elements).
To this extent, I have added a couple of tests in `lookup_test.rs` that perform lookups over a big lookup table. The speed up achieved by the optimization can be observed by running such tests before and after applying the commit introducing the optimization (that is, the "optimize lookup builder" commit with identifier 8c842a2048a0da933cd313c57ff671911438c9c6). 
This optimization might allow to significantly reduce the circuit building time when doing larger range checks or using hash functions with larger lookup tables. For example, while using 8-bit lookups by default, Monolith …

Optimize lookup builder

---

evm/src/cpu/columns/mod.rs
evm/src/cpu/gas.rs
evm/src/cpu/jumps.rs
evm/src/cpu/syscalls_exceptions.rs
evm/src/fixed_recursive_verifier.rs
evm/src/generation/mod.rs
evm/src/get_challenges.rs
evm/src/proof.rs
evm/src/recursive_verifier.rs
evm/src/witness/operation.rs
evm/src/witness/transition.rs

Following discussion in https://github.com/mir-protocol/evm-tests/issues/35, handle gas (limit/used) in two limbs.
The primary goal is for testing, as currently more than 7000 tests can't pass the check due to the recent zkEVM updates.
The additional CPU column is I think acceptable, given that we've already reduced the width by quite a bit (116 columns with this PR), and there are a few PRs opened or incoming which should bring it close to 100. In the worst case, we could always revert this PR once we get close to production-readiness?
If that's considered a too large overhead for what it brings, we could instead keep it up to date whenever there are consequent changes on `main`, and bind the test runner to this branch? Or we could go for the partial solution of just augmenting to 2 …

Make gas fit in 2 limbs

---

evm/src/generation/mpt.rs
evm/tests/log_opcode.rs

Also move them behind a transaction_testing module for clarity on their expected usage.
@wborgeaud Would you mind having another look?

Derive clone for txn RLP structs

---

evm/src/generation/mpt.rs

The current custom encoding for empty `to` fields is erroneous, as it will attempt to end early the RLP processing, leading the final RLP string to miss the length of the final element (the `s` field of the signature) in the prefix computation.
This can be tested for instance by getting an arbitrary transaction, replace the `to` field with `AddressOption(None)` encode it, and try to decode it with an online tool like https://toolkit.abdk.consulting/ethereum#rlp.

Fix encoding for empty recipient

---

evm/src/all_stark.rs
evm/src/arithmetic/arithmetic_stark.rs
evm/src/arithmetic/columns.rs
evm/src/arithmetic/divmod.rs
evm/src/arithmetic/mod.rs
evm/src/arithmetic/modular.rs
evm/src/arithmetic/mul.rs
evm/src/arithmetic/shift.rs
evm/src/cpu/cpu_stark.rs
evm/src/witness/operation.rs

This PR changes the way SHL and SHR are generated so that all the CPU CTLs looking into `ArithmeticStark` have the same form, and we can save one CTL.
Here, shift operations are generated on the arithmetic side rather on the CPU side. This leads to specific constraints for the shift operations, since now, the first input is `shift` rather than `1 << shift`. 
The three input registers are used in the Arithmetic STARK: the first is `shift`, the second is the input, and the third is `1 << shift`.
This way, we can have the same CTL shape for all arithmetic operations, and it removes the special shift CTL.
@unzvfu Would mind looking at this if you have the time?

Remove extra SHL/SHR CTL.

---

evm/src/all_stark.rs
evm/src/keccak/columns.rs
evm/src/keccak/keccak_stark.rs
evm/src/keccak_sponge/keccak_sponge_stark.rs
evm/src/witness/traces.rs
evm/src/witness/util.rs

This PR removes the 50 `reg_preimage` columns in `KeccakStark`, at the cost of:
- introducing 1 timestamp column (to check the link between inputs and outputs by validating the timestamp against `KeccakSpongeStark`),
- separating the inputs from the outputs in `Keccak`'s CTLs (so one extra CTL with one looked `Keccak` table and one looking `KeccakSponge` table).

Remove reg_preimage columns in KeccakStark

---

evm/src/cpu/shift.rs
evm/src/witness/operation.rs

This fixes the shift constraints for displacement > $2^{32}$.
The issue is that when calling `append_shift` in `witness/operations.rs`, we don't perform a READ if the displacement does not fit in the lowest limb, but this isn't properly represented in constraints.
We also didn't compute the general column for the inverse of the high_limbs_sum, which is necessary for satisfying some of the constraints.
I've also added constraint comments on the recursive side for easy reading and consistency with how the other modules are documented.
@unzvfu Would you mind confirming?

Fix shift constraint

---

evm/src/cpu/columns/general.rs
evm/src/cpu/columns/mod.rs
evm/src/cpu/columns/ops.rs
evm/src/cpu/cpu_stark.rs
evm/src/cpu/decode.rs
evm/src/cpu/membus.rs
evm/src/get_challenges.rs
evm/src/proof.rs
evm/src/recursive_verifier.rs

We thought it'd be probably good to cleanup the codebase with what's most likely not going to be used anymore.
That's not all, but that's a start at least.

Remove some dead_code in EVM crate

---

evm/src/cpu/kernel/asm/core/process_txn.asm

`Syscalls` push a default 1 as txn `status` at the end of their execution, prior jumping to `terminate_common`. However the latter may end up in failure, while the `status` stored in the stack is never modified to be changed to 0.
Detected through all the `CREATE_ContractRETURNBigOffset` variants (now passing).
Also fixes `codesizeOOGInvalidSize` variants and most of previously failing `CreateOOGFromEOARefunds` variants.

Make sure success is 0 in contract failure

---

evm/src/cpu/kernel/asm/core/create_receipt.asm

We noticed a few evm-tests failing (such as Create2OOGFromCallRefunds_{16, 17}) when the logs are non-empty and the status of the transaction is 0. This is because we set the length of the logs to 0 but not their payload's length, which is later used for encoding the receipts. This PR fixes this by setting the logs' payload length to 0 when the status is 0.

Fix failed receipt.

---

evm/src/cpu/kernel/asm/memory/metadata.asm

Wrong stack at the end of `sys_blockhash`. Fixes (at least) one `stEIP150singleCodeGasPrices/gasCostBerlin` test.

Fix sys_blockhash

---

evm/src/cpu/kernel/aggregator.rs
evm/src/cpu/kernel/asm/core/log.asm
evm/src/cpu/kernel/asm/journal/log.asm
evm/src/cpu/kernel/asm/journal/revert.asm
evm/src/cpu/kernel/constants/journal_entry.rs

We noticed a few tests failing, such as `logInOOG_Call` due to logs happening within a CALL, and not reverting. To fix this, this PR adds logs to the journal so they can be reverted when necessary.

Add journal entry for logs

---

evm/src/cpu/kernel/asm/mpt/delete/delete_branch.asm
evm/src/cpu/kernel/tests/mpt/delete.rs

Add the assumption that whenever we have
``` 
B
/ \
H   N
```
and want to delete `N`, the hash node `H` does not contain an extension or leaf node. The result is then just
```
E
|
H
```
This assumption should be satisfied in the EVM if the partial tries are correctly computed.
Closes #1275.

Fix hash node case in `mpt_delete_branch`

---

evm/src/cpu/kernel/asm/core/terminate.asm

Implements @hratoanina's suggestion in #1106 to handle gas overflowing the gaslimit caused by native instructions.
closes #1106

Check gas in sys_stop

---

plonky2/src/plonk/config.rs

I noticed that when padding a hash, we pad to a multiple of `WIDTH` instead of `RATE`. I believe this is a mistake that this PR fixes. @dlubarov  Would you mind letting me know whether I'm missing something?

Pad according to RATE rather than WIDTH

---

evm/src/cpu/kernel/asm/curve/bn254/curve_arithmetic/glv.asm
evm/src/cpu/kernel/asm/curve/secp256k1/curve_add.asm
evm/src/cpu/kernel/asm/curve/secp256k1/glv.asm
evm/src/cpu/kernel/interpreter.rs
evm/src/cpu/kernel/opcodes.rs
evm/src/witness/gas.rs

Fixes TODOs related to adding `SUBMOD` in kernel operations.
Also manually update the stack instead of calling `%submod_secp_base` (as it incurs 2 SWAPs).
Saves around 4k CPU cycles for `simple_transfer` and `add11_yml`.

Use `SUBMOD` in kernel

---

evm/src/cpu/kernel/asm/core/create_receipt.asm

We currently zeroize one byte of the bloom filter at a time.
This improves the reset by proceeding by chunks of 32 bytes and calling `MSTORE_32BYTES` with value 0.
Saves around 2.2k CPU cycles / 8.8k Memory rows.

Amortize bloom filter reset at end of txn

---

evm/src/cpu/kernel/asm/memory/memcpy.asm
evm/src/cpu/kernel/asm/memory/syscalls.asm
evm/src/cpu/kernel/asm/mpt/hash/hash_trie_specific.asm
evm/src/cpu/kernel/asm/transactions/router.asm

The current `%memcpy` is quite wasteful for sequence of bytes, which is being used twice for transaction encoding.
I suggest having a dedicated macro `memcpy_bytes` for those, which packs the bytes by sequences of length 32 (or smaller for the last chunk), and rely on `MLOAD_32BYTES` / `MSTORE_32BYTES` to amortize the CPU / Memory overhead.
On `add11_yml`, I am getting a mild 4.7% reduction in CPU cycle count, but for larger transactions, the impact is better.
For the more extreme example (`Shanghai/creationTxInitCodeSizeLimit_d0g0v0_Shanghai.json`), this is pruning almost ***30%*** of both CPU and Memory traces, with number of CPU cycles going from 8_758_697 to 6_192_428 and Memory rows going from 23_644_152 to 16_807_024.

Add macro for copying sequences of bytes

---

evm/src/cpu/kernel/asm/account_code.asm
evm/src/cpu/kernel/asm/bignum/util.asm
evm/src/cpu/kernel/asm/memory/memset.asm
evm/src/cpu/kernel/asm/memory/syscalls.asm

I realized in #1304 that a similar logic could be done with `memset`.
As it is always used to write zeroes, I just replaced the original label to be effective everywhere.
An example on `stPreCompiledContracts/modexp_d0g0v0_Shanghai` test:
before: `{ arithmetic_len: 141396, byte_packing_len: 3644, cpu_len: 899924, keccak_len: 12600, keccak_sponge_len: 525, logic_len: 3782, memory_len: 2447097 }`
after: `{ arithmetic_len: 125741, byte_packing_len: 11724, cpu_len: 740850, keccak_len: 12600, keccak_sponge_len: 525, logic_len: 3782, memory_len: 2028462 }`
i.e. 17.7% reduction in CPU / 17.1% reduction in Memory, pre padding.

Speed-up memset and fix it to write 0 values

---

evm/src/cpu/kernel/asm/memory/memcpy.asm
evm/src/cpu/kernel/asm/memory/memset.asm

An oversight from #1304 (that isn't part of the last comment there), but copying empty sequences (either through a dumb call to one of the syscalls, or if the sequence length is a multiple of 32 bytes), would result in CTL failure as the byte_packing table isn't supposed to have empty sequences.
example: `codecopy_d3g0v0_Shanghai.json`

Handle empty case for `memcpy_bytes`

---

evm/src/cpu/dup_swap.rs

Some memory channels weren't disabled for the DUP and SWAP instructions.

Add missing constraints for DUP/SWAP

---

evm/src/cpu/bootstrap_kernel.rs
evm/src/cpu/cpu_stark.rs
evm/src/cpu/simple_logic/eq_iszero.rs
evm/src/cpu/simple_logic/mod.rs
evm/src/cpu/simple_logic/not.rs
evm/src/cpu/stack.rs
evm/src/witness/operation.rs
evm/src/witness/util.rs

Since #1229 introduced multi-row CTLs, it is no longer necessary to have the outputs of operations (such as arithmetic ones) on the same row in the CPU, since we can use the next row for CTLs and constraints. This PR thus removes the need for the `new_stack_top_channel` field in `Stackbehavior`.

Remove new_stack_top_channel from StackBehavior

---

evm/src/cpu/kernel/asm/core/call.asm
evm/src/cpu/kernel/asm/core/create.asm
evm/src/cpu/kernel/asm/core/create_receipt.asm
evm/src/cpu/kernel/asm/core/precompiles/id.asm
evm/src/cpu/kernel/asm/core/precompiles/main.asm
evm/src/cpu/kernel/asm/core/precompiles/rip160.asm
evm/src/cpu/kernel/asm/core/precompiles/sha256.asm
evm/src/cpu/kernel/asm/core/process_txn.asm
evm/src/cpu/kernel/asm/core/terminate.asm
evm/src/cpu/kernel/asm/rlp/encode_rlp_string.asm
evm/src/cpu/kernel/asm/transactions/common_decoding.asm
evm/src/cpu/kernel/asm/transactions/type_1.asm
evm/src/cpu/kernel/asm/transactions/type_2.asm

Follow up from #1304, it seems that actually almost all calls to `memcpy` are dealing with bytes, for which we can then replace the macro call to `memcpy_bytes`.
Below are a few results before/after this change:
```asm
simple_transfer: (CPU -> 17.2% reduction)
Trace lengths (before padding): { arithmetic_len: 11629, byte_packing_len: 1863, cpu_len: 78144, keccak_len: 12072, keccak_sponge_len: 503, logic_len: 3549, memory_len: 300598 }
Trace lengths (before padding): { arithmetic_len: 10149, byte_packing_len: 2895, cpu_len: 64732, keccak_len: 12072, keccak_sponge_len: 503, logic_len: 3549, memory_len: 264874 }
add11_yml: (CPU -> 13.9% reduction)
{ arithmetic_len: 13856, byte_packing_len: 2491, cpu_len: 95679, keccak_len: 12384, keccak_sponge_len: 516, logic_len: 3772, memory_len: 346087 } …
```

Use `memcpy_bytes` whenever possible

---

evm/src/keccak_sponge/columns.rs
evm/src/keccak_sponge/keccak_sponge_stark.rs

We noticed that in `KeccakSpongeStark`, we are storing the `len` in an extra column and check that the final number of absorbed bytes is equal to the length, and that the length corresponds to the value in `CpuStark`. 
This should actually be doable without storing the length in `KeccakSpongeStark`: we can directly reconstruct it using `already_absorbed_bytes` and `is_final_input_len`, and then compare that linear combination to the value in `CpuStark`. 
This results in one less column in `KeccakSpongeStark` and fewer constraints in this PR.

Remove `len` column in `KeccakSpongeStark`

---

evm/src/cpu/kernel/asm/core/create_contract_account.asm
evm/src/cpu/kernel/asm/core/selfdestruct_list.asm
evm/src/cpu/kernel/asm/core/terminate.asm
evm/src/cpu/kernel/asm/core/transfer.asm
evm/src/cpu/kernel/asm/journal/account_created.asm
evm/src/cpu/kernel/constants/global_metadata.rs
evm/src/memory/segments.rs

Tracking issue: https://github.com/0xPolygonZero/plonky2/issues/1268
Be advised that some EVM tests don't pass. However, I believe that the tests aren't correct.
Out of select tests (everything [in here ](https://github.com/topos-protocol/evm-tests-suite-parsed/tree/selfdestruct/selfDestruct/GeneralStateTests) except in the Cancun folder, which deals with MEMCOPY tests), only three don't pass:
`doubleSelfdestructTest_d4g0v0_Cancun`, `doubleSelfdestructTest_d5g0v0_Cancun` and `doubleSelfdestructTest_d6g0v0_Cancun`. 
An issue was opened here: https://github.com/ethereum/tests/issues/1318

Implement EIP-6780 (new SELFDESTRUCT)

---

evm/src/cpu/kernel/asm/memory/memcpy.asm
evm/src/cpu/kernel/asm/memory/memset.asm

Same trick as in `memcpy`.
Additionally, performs `LT` against 33 instead of 32, as otherwise for a chunk of exactly 32 bytes, we'd go through the loop twice.

minor: Move empty check of `memset` inside final iteration

---

evm/src/cpu/clock.rs
evm/src/cpu/cpu_stark.rs
evm/src/cpu/mod.rs

The `clock` register wasn't constrained. We might need to have a more complex logic to update it in future PRs, so I added the constraints in a dedicated file.

Constrain clock

---

evm/src/keccak_sponge/columns.rs
evm/src/keccak_sponge/keccak_sponge_stark.rs

Range-checks the `KeccakSpongeStark` `block_bytes` values to be fitting in a `u8`.
This, along with what's already there on `Arithmetic` / `BytePacking` tables, and assuming the TODO for `PUSH` constraints is implemented, should be enough to ensure that all memory values being written are indeed of the correct form (i.e. each decomposed limb holds at most 32 bits).

Range-check keccak sponge inputs to bytes

---

evm/src/generation/mpt.rs

The parser currently only supports legacy receipts, for which the byte sequence is an actual RLP encoding. For non-legacy receipts, similarly to non-legacy transactions, the txn type should be prepended.

Fix parsing of non-legacy receipts

---

evm/src/all_stark.rs
evm/src/byte_packing/byte_packing_stark.rs
evm/src/cpu/cpu_stark.rs
evm/src/cpu/stack.rs
evm/src/cross_table_lookup.rs
evm/src/witness/operation.rs
evm/tests/empty_txn_list.rs
evm/tests/log_opcode.rs

This constrains `PUSH` internal reads to be bytes, by delegating the check to `BytePackingStark`
closes #1150 
closes #1325 as this won't be an issue anymore after this.

Add push constraints

---

evm/src/cpu/kernel/asm/core/exception.asm
evm/src/cpu/kernel/assembler.rs
evm/src/cpu/kernel/ast.rs
evm/src/cpu/kernel/evm_asm.pest
evm/src/cpu/kernel/parser.rs
evm/src/witness/transition.rs

Closes https://github.com/0xPolygonZero/plonky2/issues/1298
It's only been tested with William's (corrected) infinite loop test, but it passes fine.
One issue is the `gas_cost_for_opcode` table in the kernel. It should use the gas constants (`@GAS_VERYLOW` etc.) but apparently the parser doesn't like anything else than literals after the `BYTES` keyword. @wborgeaud Would you happen to know how to get around it?

Implement out of gas exception

---

evm/src/fixed_recursive_verifier.rs
evm/tests/empty_txn_list.rs
evm/tests/log_opcode.rs

This PR changes the arguments of `prove_aggregation` to pass both `PublicValues` associated to the two inner proofs being combined, so that the logic of selecting a field from one `pv` or the other is done internally and is simpler from outside.
cc @BGluth

Merge public values inside prove_aggreg

---

evm/src/arithmetic/columns.rs
evm/src/cpu/clock.rs
evm/src/cpu/columns/general.rs
evm/src/cpu/columns/mod.rs
evm/src/cpu/columns/ops.rs
evm/src/cpu/cpu_stark.rs
evm/src/cpu/kernel/constants/exc_bitfields.rs
evm/src/cpu/membus.rs
evm/src/cpu/stack_bounds.rs
evm/src/extension_tower.rs
evm/src/keccak/columns.rs
evm/src/keccak_sponge/columns.rs
evm/src/logic.rs
evm/src/memory/segments.rs
evm/src/proof.rs
evm/src/witness/memory.rs

Seems some remaining public items are causing issues when using plonky2_evm as dependency, see: https://github.com/0xPolygonZero/evm-tests/actions/runs/6908569164/job/18798130299.

Reduce visibility

---

evm/src/byte_packing/byte_packing_stark.rs
evm/src/keccak_sponge/keccak_sponge_stark.rs
evm/src/memory/memory_stark.rs

@pgebheim We noticed that there were some missing constraints to ensure that the tables against which we perform a range check are correctly constructed. This PR addresses this issue.

Add range check constraints for the looked table

---

evm/src/cpu/kernel/interpreter.rs
evm/src/cpu/kernel/tests/account_code.rs

We noticed that in the interpreter, the program counter that is stored corresponds to `program_counter + 1` outside of the interpreter, so we fix this in `run_syscall` on the interpreter side. We also remove the unnecessary `self.run` in `run_syscall`. We update the `sload` test to catch this error.

Fix run_syscall in interpreter.

---

evm/src/cpu/kernel/asm/mpt/hex_prefix.asm
evm/src/cpu/kernel/tests/kernel_consistency.rs
evm/src/cpu/kernel/tests/mod.rs
evm/src/generation/mod.rs

Attempt at fixing the Kernel hash discrepancy across runs.
Print the `KERNEL` code hash in say, `prove_with_outputs()`, and then run:
```bash
for i in {0..10}; do cargo test --release --test simple_transfer; done
```
Upon inspection of the different code segments per parsed file, it appears that the inconsistency was coming from `hex_prefix.asm`, more particularly on the `%stack` macro which for some reasons seems to not be deterministic. I've replaced them by hardcoding what the optimizer had deduced.
On this branch, I've ran the above command 40 times and got the same hash every time.
I also:
- changed a variable name, that was identical to a `label` and could have messed things up
- removed the duplicate copy of the kernel code in `initialize_kernel_code()` as this is already being …

Fix kernel codehash discrepancy

---

evm/src/cpu/contextops.rs

Some constraints for SET_CONTEXT were incorrect. Instead of checking that the new stack top was what was read in memory channel 3, we were only checking the first limb and forcing the other 7 to be 0.
Additionally, the zero-checking of the high limbs of value for one-limb quantities (like the stack length, or the context) wasn't done.

Fix set_context constraints

---

evm/src/cpu/kernel/cost_estimator.rs
evm/src/cpu/kernel/stack/stack_manipulation.rs

Updates the cost evaluation for stack operations, as some have changed since the top of the stack move to CPU table.
Also removes the TODO related to PUSH cost as it seems correct now that PUSH constraints induce 1 Memory read per byte.
Gains are clearly negligible, but at least it's coherent with the underlying implementation.
closes #1332

Update stack op cost

---

evm/src/fixed_recursive_verifier.rs
evm/src/proof.rs
evm/src/util.rs
evm/tests/empty_txn_list.rs

This allows to retrieve the `PublicValues` stored in the public inputs of a proof, regardless of its aggregation level.
I haven't touched the existing API for the prover, as we may still prefer to just keep the returned `PublicValues` but this at least allows a verifier to recover them if needed (as they are kind of "decoupled" from their proofs for now).

Implement `PublicValues` retrieval from public inputs

---

evm/src/cpu/kernel/asm/rlp/decode.asm

This removes 1677 CPU cycles for erc20.

Use mstore_32bytes to optimize decode_int_given_len

---

evm/src/cpu/kernel/tests/bn254.rs
evm/src/cpu/kernel/tests/hash.rs
evm/src/stark.rs
starky/src/stark.rs

walk through code catch some typo
- yeld_constr -> yield_constr
- interpeter -> interpreter
replaced this in  all doc

chore: fix some comment typos

---

evm/src/byte_packing/byte_packing_stark.rs

This PR adds a check that all value limbs in `BytePackingStark` after the last one (i.e. when the length is `i`, all value limbs with index  `i` or higher are 0).

Check that limbs after the length are 0

---

evm/src/fixed_recursive_verifier.rs
evm/src/generation/mod.rs
evm/src/get_challenges.rs
evm/src/proof.rs
evm/src/recursive_verifier.rs
evm/tests/add11_yml.rs
evm/tests/basic_smart_contract.rs
evm/tests/empty_txn_list.rs
evm/tests/erc20.rs
evm/tests/log_opcode.rs
evm/tests/self_balance_gas_cost.rs
evm/tests/selfdestruct.rs
evm/tests/simple_transfer.rs
evm/tests/withdrawals.rs

This changes the notion of `genesis` block for a `checkpoint` block, allowing to pass a `None` argument not only for the first block post-genesis but at any chosen checkpoint height.
- removed constraint on the `checkpoint` block number to be 0. It is still checked to be 1 less than the current block proof.
- binds `block_proof` output `PublicValues` to what's encoded, similarly to how it's done at the aggregation level, instead of letting them be arbitrary.
- added an example of changing the checkpoint for a new block in `log_opcode`
@LindaGuiga Would you mind reviewing?
cc @BGluth, this would also allow us to not have to restart from block 1 whenever we want to test block N :)

Add `Checkpoint` heights

---

evm/README.md
evm/spec/cpulogic.tex
evm/spec/mpts.tex

some typo fix, nothing major
have a nice week-end

chore(evm): minor typo fix

---

field/src/goldilocks_field.rs

Fixes `index out of bounds: the len is 0 but the index is 0` error for `GoldilocksField::from_noncanonical_biguint(BigUint::zero())`

fix: make `from_noncanonical_biguint` work for zero

---

evm/src/fixed_recursive_verifier.rs
evm/src/generation/mod.rs
evm/src/keccak/keccak_stark.rs
evm/src/prover.rs
evm/tests/add11_yml.rs
evm/tests/basic_smart_contract.rs
evm/tests/empty_txn_list.rs
evm/tests/erc20.rs
evm/tests/log_opcode.rs
evm/tests/self_balance_gas_cost.rs
evm/tests/selfdestruct.rs
evm/tests/simple_transfer.rs
evm/tests/withdrawals.rs

@cpubot: I'm not super satisfied with how it looks, but it's probably conceptually the simplest way to do what you wanted to notify workers to abort early. Does this look good on your end? 
Note that the logic is only present for transaction proofs (i.e. `prove_root()`) as aggregation / block proofs are orders of magnitude faster and don't need this special handling.

Add aborting signal

---

plonky2/src/iop/witness.rs

With this minor change, user can visualize their trace in following tool without code modification in plonky2 repo.
https://plonk.pro/play/index.html#/analyzer/plonky2

add Debug trait to PartitionWitness to enable trace information output

---

evm/src/cross_table_lookup.rs
evm/src/fixed_recursive_verifier.rs
evm/src/proof.rs
evm/src/prover.rs
evm/src/recursive_verifier.rs
evm/tests/empty_txn_list.rs

This PR:
- Allows to write/load only upper circuits when serializing/deserializing the prover state (i.e. by skipping all the STARK table circuits).
- Adds an alternative method to prove txns (`prove_root_light()`) by passing an additional path to a folder containing all different table circuits. After generating the initial STARK, the prover will read only the necessary circuit files, deserializes them and process to recursion. The files are expected to be stored at `initial_path/TableName_size.ser`.
- Also removes the `expand` methods, which were only added previously for easier testing but ended up never being really useful.
cc @cpubot: For zero-bin / eth-tx-proof, we would:
- still be generating the initial prover state as usual.
- instead of writing the entire state in a single file, …

Add alternative method to prove txs without pre-loaded table circuits

---

evm/src/cpu/columns/general.rs

Latest clippy is complaining wrongly about unconditional recursion. 
```bash
error: function cannot return without recursing
--> evm/src/cpu/columns/general.rs:79:5
|
79 | /     fn eq(&self, other: &Self) -> bool {
80 | |         let self_arr: &[T; NUM_SHARED_COLUMNS] = self.borrow();
81 | |         let other_arr: &[T; NUM_SHARED_COLUMNS] = other.borrow();
82 | |         self_arr == other_arr
83 | |     }
| |_____^
|
note: recursive call site
--> evm/src/cpu/columns/general.rs:82:9
|
82 |         self_arr == other_arr
|         ^^^^^^^^^^^^^^^^^^^^^
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unconditional_recursion
= note: `-D clippy::unconditional-recursion` implied by `-D warnings`
= help: to override `-D warnings` add …
```

Pacify latest clippy

---

evm/src/lookup.rs

I noticed that in the LogUp checks for range-checks, we do not check that the `Z` polynomial is initialized to 0.

Add initial constraint z polynomial

---

evm/src/cpu/kernel/asm/core/terminate.asm

Now that native instruction gas check is implemented, this sanity check is not needed as we would abort early in case of OOG.

Remove gas check in sys_stop

---

evm/src/cpu/kernel/asm/memory/core.asm
evm/src/cpu/kernel/asm/mpt/hash/hash.asm
evm/src/cpu/kernel/asm/mpt/hash/hash_trie_specific.asm
evm/src/cpu/kernel/asm/mpt/hex_prefix.asm
evm/src/cpu/kernel/asm/mpt/util.asm
evm/src/cpu/kernel/asm/rlp/encode.asm

Following #1426, `%mstore_rlp`'s name is not really meaningful, as it only performs `SWAP MSTORE_GENERAL`.
Additionally, most calls can be changed to a single call to `MSTORE_GENERAL` instead by reordering previous stack operations. This addresses it and renames the last remaining calls to `%mstore_rlp` as `%swap_mstore` for clarity.

Improve some calls to `%mstore_rlp`

---

evm/src/arithmetic/arithmetic_stark.rs
evm/src/arithmetic/columns.rs
evm/src/memory/memory_stark.rs

The arithmetic flags were not constrained to be boolean.
Also add a comment on the Memory side for clarity on the `IS_READ` boolean implicit constraint.

Add Boolean constraints for `ArithmeticStark`

---

evm/src/cpu/kernel/asm/bignum/cmp.asm
evm/src/cpu/kernel/asm/bignum/shr.asm
evm/src/cpu/kernel/asm/bloom_filter.asm
evm/src/cpu/kernel/asm/core/gas.asm
evm/src/cpu/kernel/asm/curve/secp256k1/ecrecover.asm
evm/src/cpu/kernel/asm/exp.asm
evm/src/cpu/kernel/asm/hash/blake2/compression.asm
evm/src/cpu/kernel/asm/hash/sha2/main.asm
evm/src/cpu/kernel/asm/hash/sha2/ops.asm
evm/src/cpu/kernel/asm/hash/sha2/write_length.asm
evm/src/cpu/kernel/asm/journal/journal.asm
evm/src/cpu/kernel/asm/journal/log.asm
evm/src/cpu/kernel/asm/memory/metadata.asm
evm/src/cpu/kernel/asm/rlp/encode.asm
evm/src/cpu/kernel/asm/rlp/encode_rlp_scalar.asm
evm/src/cpu/kernel/asm/rlp/num_bytes.asm
evm/src/cpu/kernel/asm/transactions/router.asm
evm/src/cpu/kernel/asm/transactions/type_0.asm
evm/src/cpu/kernel/asm/transactions/type_1.asm
evm/src/cpu/kernel/asm/transactions/type_2.asm
evm/src/cpu/kernel/asm/util/basic_macros.asm
evm/src/cpu/kernel/asm/util/math.asm

Some light tweaks on the kernel side
- %decrement / %div / %mod -> try preventing the SWAP call
- %div_const(pow_two) -> %shr_const (no SWAP)
- sibling of `encode_rlp_scalar` with swapped inputs (as the `%stack` macro inside becomes actually cheaper)

Free up some CPU cycles

---

evm/src/cpu/syscalls_exceptions.rs

One auditor noticed these two flags weren't properly constrained to be boolean.
All other flags are individually constrained in `decode` CPU submodule.

Constrain `syscall` / `exceptions` filter to be boolean

---

evm/src/cpu/kernel/interpreter.rs
evm/src/cpu/kernel/tests/add11.rs
evm/src/generation/state.rs

This PR adds an initilization method to the interpreter based on `GenerationInputs`. Given a new state, it updates it following `apply_metadata_and_tries_memops` on the STARK side. It also updates the `rlp` and `withdrawal` prover inputs, as well as the MPT roots, as is done when initializing a `GenerationState` on the STARK side.
This should make running a variety of EVM tests easier on the interpreter side.

Interpreter GenerationInputs

---

evm/src/memory/memory_stark.rs

Small PR to fix `fill_gaps`: the dummy read's value was set to the value in `next`, when it should be set to 0. This bug caused an `msize` test to fail in the EVM suite.

Fix fill_gaps

---

plonky2/src/plonk/circuit_builder.rs

Downstream repo's, such as [plonky2x](https://github.com/succinctlabs/succinctx/tree/main/plonky2x), need access to `add_generators`.

fix: Make `add_generators` public

---

evm/spec/framework.tex

Found few typos I corrected while reading framework.tex
Hope I could be of any help.
Have a nice week-end.

chore(evm/spec): proofreading framework.tex

---

evm/src/cpu/kernel/asm/account_code.asm
evm/src/cpu/kernel/asm/balance.asm
evm/src/cpu/kernel/asm/core/create_addresses.asm
evm/src/cpu/kernel/asm/core/jumpdest_analysis.asm
evm/src/cpu/kernel/asm/core/precompiles/blake2_f.asm
evm/src/cpu/kernel/asm/core/precompiles/bn_add.asm
evm/src/cpu/kernel/asm/core/precompiles/bn_mul.asm
evm/src/cpu/kernel/asm/core/precompiles/ecrec.asm
evm/src/cpu/kernel/asm/core/precompiles/expmod.asm
evm/src/cpu/kernel/asm/core/precompiles/rip160.asm
evm/src/cpu/kernel/asm/core/precompiles/sha256.asm
evm/src/cpu/kernel/asm/core/precompiles/snarkv.asm
evm/src/cpu/kernel/asm/main.asm
evm/src/cpu/kernel/asm/memory/core.asm
evm/src/cpu/kernel/asm/memory/packing.asm
evm/src/cpu/kernel/asm/memory/syscalls.asm
evm/src/cpu/kernel/asm/mpt/hash/hash.asm
evm/src/cpu/kernel/asm/mpt/hex_prefix.asm
evm/src/cpu/kernel/asm/mpt/insert/insert_trie_specific.asm
evm/src/cpu/kernel/asm/mpt/util.asm
evm/src/cpu/kernel/asm/rlp/encode.asm
evm/src/cpu/kernel/asm/rlp/increment_bounded_rlp.asm
evm/src/cpu/kernel/asm/util/keccak.asm
evm/src/cpu/kernel/tests/packing.rs
evm/src/cpu/kernel/tests/rlp/encode.rs

Removes some CPU cycles:
- all calls to `%mload_packing` can be directly replaced to `MLOAD_32BYTES`, no need for hook + jump
- Similarly for `%mstore_unpacking`, we can sometimes just call directly the variant if the size is known which skips going through the jumptable
- tweaked some very large stack operation in `hash.asm`, to reduce the needless overhead
Removes 1050 CPU cycles on ERC20 (much more with large MPTs)

Remove some CPU cycles

---

evm/src/cpu/kernel/asm/bloom_filter.asm
evm/src/cpu/kernel/asm/core/access_lists.asm
evm/src/cpu/kernel/asm/core/create_addresses.asm
evm/src/cpu/kernel/asm/core/create_receipt.asm
evm/src/cpu/kernel/asm/core/jumpdest_analysis.asm
evm/src/cpu/kernel/asm/core/log.asm
evm/src/cpu/kernel/asm/core/selfdestruct_list.asm
evm/src/cpu/kernel/asm/core/terminate.asm
evm/src/cpu/kernel/asm/core/touched_addresses.asm
evm/src/cpu/kernel/asm/journal/journal.asm
evm/src/cpu/kernel/asm/memory/core.asm
evm/src/cpu/kernel/asm/mpt/delete/delete_branch.asm
evm/src/cpu/kernel/asm/mpt/hex_prefix.asm
evm/src/cpu/kernel/asm/mpt/insert/insert_extension.asm
evm/src/cpu/kernel/asm/mpt/insert/insert_leaf.asm
evm/src/cpu/kernel/asm/rlp/encode.asm
evm/src/cpu/kernel/asm/util/basic_macros.asm
evm/src/cpu/kernel/asm/util/keccak.asm

- for most loops iterating over `i` until `i == len`, and reading/writing to the same memory segment, both `i` and `len` are scaled from the beginning by the corresponding segment value (and unscaled while leaving the loop)
- packs all 17 `0` writes when creating a new branch node into a single write
- removes the txn bloom segment reset post execution (we only process 1 txn per proof now)
Shaves off between 0.6% and 1.8% of CPU cycles for a set of arbitrary L1 txns, on top of #1469 (which already removed ~7%/8%).

Remove some more CPU cycles

---

.github/workflows/continuous-integration-workflow.yml

Highly inspired from foundry's CI [workflow](https://github.com/foundry-rs/foundry/blob/master/.github/workflows/test.yml).
- Fix warnings shown in CI job output (e.g. https://github.com/0xPolygonZero/plonky2/actions/runs/7558066520).
- Bump `actions/checkout` and `actions/cache` versions.
- Remove [`actions-rs/toolchain`](https://github.com/actions-rs/toolchain) and [`actions-rs/cargo`](https://github.com/actions-rs/cargo) because they are not maintained anymore since Oct 13, 2023.
- To install the rust toolchain, use [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain) instead of `actions-rs/toolchain`.
- To set up rust cache, use [`Swatinem/rust-cache`](https://github.com/Swatinem/rust-cache) instead of `actions/cache`.
- Instead of using `actions-rs/cargo` to run …

chore: update ci workflow

---

evm/src/cpu/kernel/asm/hash/sha2/compression.asm
evm/src/cpu/kernel/asm/hash/sha2/main.asm
evm/src/cpu/kernel/asm/hash/sha2/message_schedule.asm
evm/src/cpu/kernel/asm/hash/sha2/write_length.asm
evm/src/cpu/kernel/asm/memory/core.asm

Reduces the number of CPU cycles for SHA2 by 7.57% on average.

Improve SHA2 precompile

---

evm/Cargo.toml
evm/LICENSE-APACHE
evm/LICENSE-MIT
evm/README.md
evm/src/cpu/kernel/asm/bignum/add.asm
evm/src/cpu/kernel/asm/bignum/addmul.asm
evm/src/cpu/kernel/asm/bignum/cmp.asm
evm/src/cpu/kernel/asm/bignum/modmul.asm
evm/src/cpu/kernel/asm/bignum/mul.asm
evm/src/cpu/kernel/asm/bignum/shr.asm
evm/src/cpu/kernel/asm/bignum/util.asm
evm/src/cpu/kernel/asm/core/jumpdest_analysis.asm
evm/src/cpu/kernel/asm/curve/bn254/curve_arithmetic/final_exponent.asm
evm/src/cpu/kernel/asm/curve/bn254/curve_arithmetic/miller_loop.asm
evm/src/cpu/kernel/asm/curve/bn254/curve_arithmetic/pairing.asm
evm/src/cpu/kernel/asm/curve/bn254/field_arithmetic/inverse.asm
evm/src/cpu/kernel/asm/curve/bn254/field_arithmetic/util.asm
evm/src/cpu/kernel/asm/hash/blake2/addresses.asm
evm/src/cpu/kernel/asm/hash/sha2/compression.asm
evm/src/cpu/kernel/asm/hash/sha2/main.asm
evm/src/cpu/kernel/asm/hash/sha2/message_schedule.asm
evm/src/cpu/kernel/asm/hash/sha2/write_length.asm
evm/src/cpu/kernel/asm/memory/core.asm
evm/src/cpu/kernel/asm/util/basic_macros.asm
evm/src/cpu/kernel/interpreter.rs
evm/src/cpu/kernel/tests/core/jumpdest_analysis.rs
evm/src/generation/mod.rs
evm/src/generation/prover_input.rs
evm/src/generation/state.rs

Brings latest changes from `main` before final freeze of the `audit/rc2` branch.
Includes:
- pairing precompile optimization (#1476 in the continuation of #1477, #1480, #1482)
- fix `jumpdest_analysis` edge case

Fast-forward `main` to `audit/rc2`

---

evm/tests/log_opcode.rs

Lates plonky2 optimizations broke `log_opcode` by requiring smaller circuit sizes than the ones currently specified.

Fix recursive circuit ranges in tests

---

plonky2/Cargo.toml
plonky2/src/fri/reduction_strategies.rs
plonky2/src/util/timing.rs

Use web-time crate (https://github.com/daxpedda/web-time) instead of std version. It works for wasm32 targets too. If target support time in std then it's just an alias to that.

Use web-time crate

---

plonky2/src/gadgets/split_base.rs
plonky2/src/gates/base_sum.rs

`impl_generator_serializer!` matches generator Id to get correct types. You would need different Ids for different bases if you wanna use `impl_generator_serializer` for these generators with different bases.
For example if your circuit uses `BaseSplitGenerator<2>` and `BaseSplitGenerator<4>` something like the snippet below:
```
impl_generator_serializer! {
CustomGeneratorSerializer
BaseSplitGenerator<2>,
BaseSplitGenerator<4>
}
```
would lead to incorrect generation of `ProverOnlyCircuitData` when reconstructed using `ProverOnlyCircuitData::from_bytes(..)`
CC: @ultrainstinct30

Fix BaseSumGenerator and BaseSplitGenerator Ids

---

evm/src/all_stark.rs
evm/src/arithmetic/arithmetic_stark.rs
evm/src/cpu/cpu_stark.rs
evm/src/cross_table_lookup.rs
evm/src/fixed_recursive_verifier.rs
evm/src/prover.rs
evm/src/recursive_verifier.rs
evm/src/verifier.rs

Make CTLs generic in the number of tables they are working on, instead of being pegged to the `Table` enum with `NUM_TABLES` variants, in preparation for the code migration.

Make CTLs more generic

---

evm/src/cross_table_lookup.rs
evm/src/fixed_recursive_verifier.rs
evm/src/get_challenges.rs
evm/src/proof.rs
evm/src/prover.rs
evm/src/recursive_verifier.rs
evm/src/verifier.rs

`StarkProofWithMetadata` exists to combine a `proof` and a `init_challenger_state`. The latter is never used, and would be useful if we were proving each table in parallel after generating the CTL data, which we are not (they are proven sequentially).
This PR removes `StarkProofWithMetadata` and `StarkProofWithMetadataTarget`, and replaces them with the regular `StarkProof` and `StarkProofTarget`.

Remove `StarkProofWithMetadata`

---

.github/workflows/continuous-integration-workflow.yml
rust-toolchain

Overnight nightly changes broke compilation because of the `stdsimd` feature.
See: 
- https://github.com/0xPolygonZero/plonky2/actions/runs/7800550002/job/21273621246
- https://github.com/tkaitchuck/aHash/issues/200
This pins the nightly version to 2024-02-01.

Pin nightly version to 2024-02-01

---

.github/workflows/continuous-integration-workflow.yml
plonky2/src/gadgets/interpolation.rs
plonky2/src/gates/poseidon.rs
plonky2/src/hash/path_compression.rs
plonky2/src/hash/poseidon.rs
plonky2/src/hash/poseidon_goldilocks.rs
plonky2/src/iop/challenger.rs
plonky2/src/lookup_test.rs
plonky2/src/plonk/proof.rs
plonky2/src/recursion/conditional_recursive_verifier.rs
plonky2/src/recursion/cyclic_recursion.rs
plonky2/src/recursion/recursive_verifier.rs
plonky2/src/util/mod.rs
plonky2/src/util/partial_products.rs

We currently do check that `plonky` and `starky` crates compile well in `no-std` for WASM targets, but it'd be nice to also make sure we can actually run their test suites in `no-std` to make sure the internal logic isn't broken.\
This PR fixes a bunch of missing conditional imports to make tests pass in `no-std`, and adds two more CI jobs for testing the two mentioned crates.

Fix no-std tests and add corresponding jobs in the CI

---

evm/src/cross_table_lookup.rs
evm/src/fixed_recursive_verifier.rs
evm/src/get_challenges.rs
evm/src/proof.rs
evm/src/prover.rs
evm/src/recursive_verifier.rs
evm/src/verifier.rs

Oversight from my end, we need to keep track of the initial challenger state for recursion with many tables (consistency check of the challenger across tables), so reverting past PR.

Revert "Remove StarkProofWithMetadata (#1497)"

---

evm/src/cpu/kernel/interpreter.rs
evm/src/witness/operation.rs

Now that the interpreter is aimed at being used for `jumpdest_analysis`, and soon for continuations, we need to alleviate the remaining risks of `panic` that can occur.

Remove risk of panics in interpreter

---

evm/src/get_challenges.rs

PR #1313 introduced BLOBBASEFEE (EIP-7516 for Cancun), but didn't add the new global metadata to the challenger transcript, possibly causing some soundness issues.
This addresses it.

Add `blob_basefee` to challenger transcript

---

.github/workflows/continuous-integration-workflow.yml
field/src/lib.rs
rust-toolchain

- Revert "Fix workflow"
- Revert "Fix nightly version"
- chore: remove stdsimd feature req (stabilized)
Likely requires an updated Cargo.lock file.

Fix nightly build (ahash issue)

---

maybe_rayon/src/lib.rs
plonky2/Cargo.toml

Fix build for wasm32/64-unknown-unknown without std

---

plonky2/examples/bench_recursion.rs
plonky2/examples/square_root.rs
plonky2/src/plonk/config.rs
plonky2/src/util/serialization/gate_serialization.rs
plonky2/src/util/serialization/generator_serialization.rs

Following suggestion from @cpubot, to not have to rely on the internals of the serializers when instantiating them for higher-level applications.

Implement `Default` for `DefaultGateSerializer` and `DefaultGeneratorSerializer`

---

CHANGELOG.md
starky/src/cross_table_lookup.rs

See [this PR](https://github.com/0xPolygonZero/zk_evm/pull/60) for the motivation.

chore: remove conditional compilation for debug_utils

---

field/src/extension/mod.rs
plonky2/src/hash/poseidon.rs
plonky2/src/iop/witness.rs

Clippy complaining about multiple bound locations and such

Pacify clippy with latest `nightly` toolchain

---

field/Cargo.toml
plonky2/Cargo.toml
starky/Cargo.toml

No concrete change, just adding the versions that were locally used when publishing the latest release, for ease of publishing and clarity.

Add mention to versions for local dependencies

---

CHANGELOG.md
starky/Cargo.toml

Bump `starky` to `v0.2.1`, prior to bumping `zk_evm` crates to `v0.1.1`.

Bump `starky` to v0.2.1

---

plonky2/src/gates/lookup.rs
plonky2/src/gates/lookup_table.rs
plonky2/src/plonk/copy_constraint.rs
starky/src/cross_table_lookup.rs
starky/src/lookup.rs
starky/src/permutation_stark.rs

CTL filters can already express perfectly well the behaviour that we gave for `None`.  No need to complicated anything.

Simplify types: remove option from CTL filters

---

field/src/lib.rs

Without this, compiling on AVX512 enabled machine gives an error:
```
error[E0658]: use of unstable library feature 'stdarch_x86_avx512'
```

Add stdarch_x86_avx512 feature

---

CHANGELOG.md
field/Cargo.toml
plonky2/Cargo.toml
starky/Cargo.toml

Necessary bump to allow building latest `zk_evm` binaries on architectures supporting AVX-512 instructions, like the c3d instances used for benchmarking.

Bump versions pre-release

---

starky/src/lookup.rs

This is a simpler PR to prepare the ground for https://github.com/0xPolygonZero/plonky2/pull/1575

Remove restriction to binary-only multiplicities

---

starky/src/cross_table_lookup.rs

This used to fail with an out of bounds error when `None` was passed for `ctl_extra_looking_sums`.

Fix `verify_cross_table_lookups` with no `ctl_extra_looking_sums`

---

field/src/goldilocks_extensions.rs
field/src/goldilocks_field.rs

- this is a first step towards addressing https://github.com/0xPolygonZero/plonky2/issues/850. note that `0x64fdd1a46201e246^(2^30) == 0x1000000000000` holds modulo p, as desired. we don't actually change the FFT in this PR; but this paves the way for that as a future change.
- both [Hermez](https://github.com/0xPolygonHermez/goldilocks/blob/f89eb016830f8c4301482d83691aed22e5a92742/src/goldilocks_base_field.cpp#L44) and [Miden](https://github.com/facebook/winterfell/blob/09525751727a283dfbf5e569a09909b82380e059/math/src/field/f64/mod.rs#L282) already currently use this new generator.
upon changing the main 2^32nd root of unity of Goldilocks, a few auxiliary values also need to change. these include:
- the multiplicative generator …

update 2-adic generator to `0x64fdd1a46201e246`

---

plonky2/src/plonk/circuit_builder.rs
plonky2/src/recursion/conditional_recursive_verifier.rs
plonky2/src/recursion/dummy_circuit.rs

This PR makes some methods public so they can be used on the `zk_evm` side, and creates a couple of new methods.

Changes to prepare for dummy segment removal in zk_evm's continuations

---

maybe_rayon/src/lib.rs

Since `std` doesn't exist as a cfg, `not(std)` was always true, so this does not change any behavior.
```
warning: unexpected `cfg` condition name: `std`
--> maybe_rayon/src/lib.rs:1:17
|
1 | #![cfg_attr(not(std), no_std)]
|                 ^^^
|
= help: expected names are: `clippy`, `debug_assertions`, `doc`, `docsrs`, `doctest`, `feature`, `miri`, `overflow_checks`, `panic`, `proc_macro`, `relocation_model`, `rustfmt`, `sanitize`, `sanitizer_cfi_generalize_pointers`, `sanitizer_cfi_normalize_integers`, `target_abi`, `target_arch`, `target_endian`, `target_env`, `target_family`, `target_feature`, `target_has_atomic`, `target_has_atomic_equal_alignment`, `target_has_atomic_load_store`, `target_os`, `target_pointer_width`, `target_thread_local`, `target_vendor`, `test`, `ub_checks`, …
```

fix: remove clippy unexpected_cfgs warning

---

plonky2/src/gates/selectors.rs
plonky2/src/plonk/vanishing_poly.rs
starky/src/cross_table_lookup.rs
starky/src/prover.rs

Another day another newly added clippy warning.
To review, make sure impacted documentation paragraphs are being split/combined correctly.

doc+fix: `clippy::doc-lazy-continuation`

---

starky/src/recursive_verifier.rs

The witness used in `set_stark_proof_target` is sufficient with `WitnessWrite`. `Witness` (which inherits from `WitnessWrite`) cannot be used in cases like `run_once` of `SimpleGenerator`.

change `set_stark_proof_target`'s witness to `WitnessWrite`

---

starky/src/lookup.rs

Not all `correct` cross table lookups use padding for the last row.

Fix CTL generation of last row

---

starky/src/cross_table_lookup.rs

Currently, `ctl_extra_looking_sums` corresponds to the index of the looked table. The problem with this is that it is not possible to set another `extra_looking_sums` for the same looked table. For example, in zk_evm's `keccak_stark`, there are two CTLs  for the same looked table, and therefore, it is not possible to use those two CTLs as `extra_looking_sums`. I addressed this issue by changing the type of `ctl_extra_looking_sums` to a `HashMap` similar to `check_ctl`, and making it correspond one-to-one with the index of the CTL.

Allow multiple `extra_looking_sums` for the same looked table

---

starky/README.md

doc: clarify that `zk` is disabled with `starky`

---

field/src/lib.rs

For some reason, this was disabling all unit tests in the `plonky2_field` crate.
Credits to @gio256 for noticing!

fix(field): Re-enable `alloc` for tests

---

field/src/types.rs

Adds the `Field::shifted_powers` method from [Plonky3](https://github.com/Plonky3/Plonky3/blob/fde81db95b8eeb39e07890f4099a7d59daeec52f/field/src/field.rs#L122-L127) along with a few additions to the `Powers` iterator implementation.
Please pick and choose what's useful.
`<Powers<F> as Iterator>::nth` in particular might require some tweaking:
- It currently panics if `n` overflows `u64`. This seems at least as good as the current behavior of hanging trying to compute `u64::MAX` field multiplications. But, maybe it's worth the performance hit to use `Field::exp_biguint`.
- The current implementation incurs one extra multiplication in the case of `n = 1` (e.g. `generator.powers().skip(1)`). It's possible this is the most commonly expected case and `nth` should just be removed altogether.

Add `Field::shifted_powers` and some iterator niceties

---

plonky2/src/hash/arch/x86_64/poseidon_goldilocks_avx2_bmi2.rs

Tiny chore: inline assembly is stable since Rust [1.59](https://blog.rust-lang.org/2022/02/24/Rust-1.59.0.html), so the docs from the unstable book are now split between the language reference and Rust by Example. I believe this should point to the same section as before, though.

Replace stale link

---

starky/src/get_challenges.rs
starky/src/prover.rs

Public inputs were not part of the transcript used to generate challenges.

fix(starky): observe public inputs

---

Cargo.toml
field/Cargo.toml
plonky2/Cargo.toml
plonky2/src/plonk/circuit_builder.rs
starky/Cargo.toml

Mostly for reuse on zk_evm side where we heavily use arrays of targets.

Add `connect_array` convenience method in `CircuitBuilder`

---

plonky2/src/plonk/circuit_builder.rs

Over in circuit_builder.rs,
std::time::Instant was used because of which wasm compilation was failing, using web_time solves it

changed to web-time in circuit_builder

---

.github/CODEOWNERS
plonky2/src/recursion/dummy_circuit.rs

We were using the default `common_data` to deserialize `DummyProofGenerator`, which would cause issues when using dummy proofs in a recursive scenario involving different configs.

Fix `DummyProofGenerator` serialization

---

field/src/types.rs
plonky2/src/gadgets/arithmetic_extension.rs
plonky2/src/hash/hash_types.rs

This PR adds the implementation of the `serialize` and `deserialize` traits for the `BytesHash` struct.
Since the `Keccak` hash function uses `BytesHash` as its hash type, it is now possible to serialize and deserialize proofs that use the `KeccakGoldilocksConfig`, like [in this example](https://gist.github.com/fndecroix/92b12b7a546113183314eace452ebf3e)

add serialization and deserialization for BytesHash

---

plonky2/src/gates/base_sum.rs

The BaseSplitGenerator was casting fields (which fit in `u64`) into `usize`. This doesn't work in 32-bit architectures where usize is 32 bits, like wasm32.  Keeping the value in `u64` allows it to work in 32-bit architectures.
We found this error while trying to run a recursive circuit in wasm, where the verification was failing.  This issue can be easily tested on an amd64 linux machine by compiling with the target i686 and running the tests.  Before this PR these are the tests that fail:
```
$ cargo test --release --target i686-unknown-linux-gnu
[...]
failures:
batch_fri::oracle::test::batch_prove_openings
recursion::conditional_recursive_verifier::tests::test_conditional_recursive_verifier
recursion::cyclic_recursion::tests::test_cyclic_recursion …
```

fix: use u64 in BaseSplitGenerator

---

plonky2/Cargo.toml
starky/Cargo.toml
starky/src/proof.rs

This should fix the documentation rendering issue in #1670.
Also `MultiProof` got removed so we probably could remove `MultiProofChallenges` at some point.

Fix documentation rendering

---

plonky2/src/gates/util.rs
plonky2/src/hash/arch/aarch64/poseidon_goldilocks_neon.rs
plonky2/src/hash/arch/x86_64/poseidon_goldilocks_avx2_bmi2.rs
plonky2/src/util/strided_view.rs

Fix latest clippy

---

field/README.md
maybe_rayon/README.md
plonky2/README.md
starky/README.md

Hi! I fixed broken links to license files in the `README.md` files across multiple directories. The links were pointing to incorrect paths, causing them to fail.

chore: update broken links `LICENSE`
